// src/site/components/IdleWarningDialog.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	The warning before an inactivity sign-out on the public site
	(signin-session-idle-warning-and-sso T06, REQ-SIS-003). The same wording
	and the same rules as the portal SPA's IdleWarningDialog.jsx: a countdown
	on screen, the remaining time spoken once a minute, focus on the action
	that keeps the visitor signed in, and near the cap only "Sign in again".
-->
<template>
	<div class="pq-idle-backdrop">
		<section
			role="alertdialog"
			aria-modal="true"
			aria-labelledby="pq-idle-title"
			aria-describedby="pq-idle-body"
			class="pq-idle-warning"
			data-testid="site-idle-warning">
			<h2 id="pq-idle-title" class="utrecht-heading-2">
				{{ t('You will be signed out soon') }}
			</h2>
			<p id="pq-idle-body" class="utrecht-paragraph">
				{{ sentence(left) }}
			</p>
			<p class="pq-idle-spoken" aria-live="polite">
				{{ sentence(Math.ceil(Math.max(0, left) / 60) * 60) }}
			</p>
			<div class="pq-idle-buttons">
				<button
					v-if="extendable"
					ref="first"
					type="button"
					class="utrecht-button utrecht-button--primary-action"
					data-testid="site-idle-stay"
					@click="$emit('stay')">
					{{ t('Stay signed in') }}
				</button>
				<button
					v-if="extendable"
					type="button"
					class="utrecht-button utrecht-button--secondary-action"
					@click="$emit('signout')">
					{{ t('Sign out') }}
				</button>
				<button
					v-else
					ref="first"
					type="button"
					class="utrecht-button utrecht-button--primary-action"
					data-testid="site-idle-sign-in-again"
					@click="$emit('signout')">
					{{ t('Sign in again') }}
				</button>
			</div>
		</section>
	</div>
</template>

<script>
import en from '../../portal/i18n/en.json'
import nl from '../../portal/i18n/nl.json'
import { canExtend, remainingText } from '../../portal/lib/idleSession.js'

const STRINGS = { en, nl }

/**
 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T06
 */
export default {
	name: 'IdleWarningDialog',

	props: {
		times: {
			type: Object,
			required: true,
		},

		locale: {
			type: String,
			default: 'nl',
		},
	},

	emits: ['stay', 'signout'],

	data() {
		return {
			left: this.times.expiresAt - Math.floor(Date.now() / 1000),
			tick: null,
		}
	},

	computed: {
		/**
		 * @return {boolean} Whether "Stay signed in" can still work.
		 *
		 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T06
		 */
		extendable() {
			return canExtend(this.times, Math.floor(Date.now() / 1000))
		},
	},

	mounted() {
		this.tick = setInterval(() => {
			this.left = this.times.expiresAt - Math.floor(Date.now() / 1000)
		}, 1000)
		this.$nextTick(() => this.$refs.first?.focus())
	},

	beforeUnmount() {
		clearInterval(this.tick)
	},

	methods: {
		/**
		 * One string in the site's language.
		 *
		 * @param {string} key The English source string.
		 * @param {object} [vars] Placeholder values.
		 * @return {string} The string.
		 *
		 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T06
		 */
		t(key, vars = {}) {
			const strings = STRINGS[this.locale] || STRINGS.nl
			return (strings[key] || key).replace(/\{(\w+)\}/g, (_, name) =>
				String(vars[name] ?? ''),
			)
		},

		/**
		 * The warning sentence for a number of seconds left.
		 *
		 * @param {number} seconds Seconds left.
		 * @return {string} The sentence.
		 *
		 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T06
		 */
		sentence(seconds) {
			const time = remainingText(seconds, this.t)
			return this.extendable
				? this.t(
						'You will be signed out in {time} because you have been inactive.',
						{ time },
					)
				: this.t(
						'Your session ends in {time}. Sign in again to keep going.',
						{ time },
					)
		},
	},
}
</script>

<style scoped>
.pq-idle-backdrop {
	position: fixed;
	inset: 0;
	z-index: 1000;
	display: flex;
	align-items: center;
	justify-content: center;
	padding: 16px;
	background: rgb(0 0 0 / 40%);
}

.pq-idle-warning {
	max-width: 32rem;
	padding: 24px;
	background: var(--utrecht-document-background-color, Canvas);
	color: var(--utrecht-document-color, CanvasText);
}

.pq-idle-buttons {
	display: flex;
	flex-wrap: wrap;
	gap: 8px;
}

.pq-idle-spoken {
	position: absolute;
	width: 1px;
	height: 1px;
	overflow: hidden;
	clip: rect(0 0 0 0);
	white-space: nowrap;
}
</style>

// src/portal/components/IdleWarningDialog.jsx
// SPDX-License-Identifier: EUPL-1.2
// Copyright (C) 2026 Conduction B.V.
//
// The warning before an inactivity sign-out (signin-session-idle-warning-and-
// sso D3, REQ-SIS-003). It counts down on screen, announces the remaining time
// once a minute through a polite live region, and puts the focus on the one
// action that keeps the resident signed in. Near the absolute cap no refresh
// can help, so the dialog then only offers to sign in again (REQ-SIS-004).

import { useEffect, useRef, useState } from 'react'
import { canExtend, remainingText } from '../lib/idleSession.js'

/**
 * The current unix time in seconds.
 *
 * @return {number}
 */
function nowSeconds() {
	return Math.floor(Date.now() / 1000)
}

/**
 * The idle warning dialog.
 *
 * @param {object} props Props.
 * @param {{expiresAt: number, hardExpiresAt: number}} props.times The session times.
 * @param {(key: string, vars?: object) => string} props.t The translator.
 * @param {() => void} props.onStay "Stay signed in": refresh the session.
 * @param {() => void} props.onSignOut "Sign out", or "Sign in again" near the cap.
 * @return {object} The dialog.
 *
 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T04
 * @spec openspec/changes/archive/2026-09-30-signin-session-idle-warning-and-sso/tasks.md#T05
 */
export default function IdleWarningDialog({ times, t, onStay, onSignOut }) {
	const [left, setLeft] = useState(() => times.expiresAt - nowSeconds())
	const firstButton = useRef(null)
	const extendable = canExtend(times, nowSeconds())

	useEffect(() => {
		if (firstButton.current) {
			firstButton.current.focus()
		}
		const tick = setInterval(() => setLeft(times.expiresAt - nowSeconds()), 1000)
		return () => clearInterval(tick)
	}, [times])

	const time = remainingText(left, t)
	// Spoken once a minute, not every second: the whole minutes left.
	const spoken = remainingText(Math.ceil(Math.max(0, left) / 60) * 60, t)
	const titleId = 'portaliq-idle-warning-title'
	const bodyId = 'portaliq-idle-warning-body'

	return (
		<div className="portaliq-idle-backdrop">
			<section
				role="alertdialog"
				aria-modal="true"
				aria-labelledby={titleId}
				aria-describedby={bodyId}
				className="portaliq-idle-warning"
				data-testid="idle-warning">
				<h2 id={titleId}>{t('You will be signed out soon')}</h2>
				<p id={bodyId}>
					{extendable
						? t('You will be signed out in {time} because you have been inactive.', { time })
						: t('Your session ends in {time}. Sign in again to keep going.', { time })}
				</p>
				<p className="portaliq-sr-only" aria-live="polite" data-testid="idle-warning-live">
					{extendable
						? t('You will be signed out in {time} because you have been inactive.', { time: spoken })
						: t('Your session ends in {time}. Sign in again to keep going.', { time: spoken })}
				</p>
				<div className="portaliq-rowaction-buttons">
					{extendable && (
						<button ref={firstButton} type="button" className="portaliq-cta" data-testid="idle-stay" onClick={onStay}>
							{t('Stay signed in')}
						</button>
					)}
					{extendable
						? (
							<button type="button" data-testid="idle-sign-out" onClick={onSignOut}>
								{t('Sign out')}
							</button>
						)
						: (
							<button ref={firstButton} type="button" className="portaliq-cta" data-testid="idle-sign-in-again" onClick={onSignOut}>
								{t('Sign in again')}
							</button>
						)}
				</div>
			</section>
		</div>
	)
}
