// src/site/components/inbox/NotificationSettings.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	The resident's notice choices at the top of the inbox
	(inbox-notifications-and-preferences, REQ-NAP-008): per kind, e-mail and
	push, each a checkbox with its own label. Collapsed by default. The push
	column shows only when the account registered a device. When the
	organisation offers the government message box, one more choice lets the
	resident switch letters to it off (inbox-berichtenbox-channel, REQ-MBC-005).
-->
<template>
	<details v-if="loaded" class="pq-notification-settings">
		<summary>{{ t('Notification settings') }}</summary>
		<form @submit.prevent="save">
			<table class="utrecht-table pq-notification-settings__table">
				<thead class="utrecht-table__header">
					<tr class="utrecht-table__row">
						<th scope="col" class="utrecht-table__header-cell">
							<span class="sr-only">{{
								t('Notification settings')
							}}</span>
						</th>
						<th
							v-for="channel in channels"
							:key="channel"
							scope="col"
							class="utrecht-table__header-cell">
							{{ channelLabel(channel) }}
						</th>
					</tr>
				</thead>
				<tbody class="utrecht-table__body">
					<tr
						v-for="kind in kinds"
						:key="kind.key"
						class="utrecht-table__row">
						<th scope="row" class="utrecht-table__header-cell">
							{{ t(kind.label) }}
						</th>
						<td
							v-for="channel in channels"
							:key="channel"
							class="utrecht-table__cell">
							<input
								:id="checkboxId(kind.key, channel)"
								type="checkbox"
								class="utrecht-checkbox"
								:checked="isOn(kind.key, channel)"
								@change="
									set(kind.key, channel, $event.target.checked)
								" />
							<label
								:for="checkboxId(kind.key, channel)"
								class="sr-only">
								{{ `${t(kind.label)}: ${channelLabel(channel)}` }}
							</label>
						</td>
					</tr>
				</tbody>
			</table>
			<p
				v-if="messageBox"
				class="utrecht-paragraph pq-notification-settings__message-box">
				<input
					id="portaliq-notify-message-box"
					type="checkbox"
					class="utrecht-checkbox"
					:checked="choices.messageBox?.enabled !== false"
					@change="setMessageBox($event.target.checked)" />
				<label
					for="portaliq-notify-message-box"
					class="utrecht-form-label utrecht-form-label--checkbox">
					{{
						t('Also send letters to {label}', {
							label: messageBox.label,
						})
					}}
				</label>
			</p>
			<button
				type="submit"
				class="utrecht-button utrecht-button--secondary-action"
				:disabled="busy">
				{{ t('Save') }}
			</button>
			<p v-if="status" class="utrecht-paragraph" role="status">
				{{ status }}
			</p>
		</form>
	</details>
</template>

<script>
import {
	messageBoxChoice,
	withMessageBoxChoice,
} from '../../../shared/messageBox.js'

/** The kinds a resident can choose for, with their English source labels. */
export const KINDS = [
	{ key: 'case.updated', label: 'Changes on your cases' },
	{ key: 'message.created', label: 'New messages' },
]

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
 */
export default {
	name: 'NotificationSettings',

	props: {
		/** The shared portal API. */
		api: { type: Object, required: true },
		/** The translator. */
		t: { type: Function, required: true },
		/** The settings answer, when the caller already has it (tests). */
		initial: { type: Object, default: null },
	},

	data() {
		return {
			loaded: this.initial,
			choices: { ...(this.initial?.preferences || {}) },
			status: '',
			busy: false,
		}
	},

	computed: {
		/**
		 * @return {Array<object>} The kinds.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		kinds() {
			return KINDS
		},

		/**
		 * @return {Array<string>} The channels: push only with a registered device.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		channels() {
			return this.loaded?.pushAvailable ? ['email', 'push'] : ['email']
		},

		/**
		 * @return {{label: string, enabled: boolean}|null} The message box choice, when offered.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		messageBox() {
			return messageBoxChoice(this.loaded)
		},
	},

	async mounted() {
		if (this.loaded) {
			return
		}
		const answer = await this.api.fetchNotificationPreferences()
		if (answer) {
			this.loaded = answer
			this.choices = { ...(answer.preferences || {}) }
		}
	},

	methods: {
		/**
		 * @param {string} channel The channel.
		 * @return {string} Its label.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		channelLabel(channel) {
			return channel === 'email' ? this.t('E-mail') : this.t('Push')
		},

		/**
		 * @param {string} kind The kind.
		 * @param {string} channel The channel.
		 * @return {string} The checkbox id.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		checkboxId(kind, channel) {
			return `portaliq-notify-${kind}-${channel}`.replace(/\./g, '-')
		},

		/**
		 * @param {string} kind The kind.
		 * @param {string} channel The channel.
		 * @return {boolean} Whether it is on; a missing choice means on.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		isOn(kind, channel) {
			return this.choices[kind]?.[channel] !== false
		},

		/**
		 * @param {string} kind The kind.
		 * @param {string} channel The channel.
		 * @param {boolean} value On or off.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		set(kind, channel, value) {
			this.status = ''
			this.choices = {
				...this.choices,
				[kind]: { ...(this.choices[kind] || {}), [channel]: value },
			}
		},

		/**
		 * @param {boolean} enabled On or off.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		setMessageBox(enabled) {
			this.status = ''
			this.choices = withMessageBoxChoice(this.choices, enabled)
		},

		/**
		 * Save the choices and say how it went.
		 *
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-notification-choices-must-be-settable-per-kind-req-srp-031
		 */
		async save() {
			this.busy = true
			const saved = await this.api.saveNotificationPreferences(this.choices)
			this.busy = false
			if (saved) {
				this.choices = { ...(saved.preferences || {}) }
				this.status = this.t('Your choices are saved.')
			} else {
				this.status = this.t('Your choices could not be saved. Try again.')
			}
		},
	},
}
</script>

<style scoped>
.pq-notification-settings {
	margin-block-end: 16px;
}

.pq-notification-settings summary {
	cursor: pointer;
	font-weight: bold;
}
</style>

// src/portal/components/NotificationSettings.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// The resident's notice choices on the inbox page
// (inbox-notifications-and-preferences, REQ-NAP-008): per kind, e-mail and
// push, each a checkbox with its own label. Collapsed by default. The push
// column shows only when the account registered a device. The inbox message
// itself is not a choice: it is the record of what happened. When the
// organisation offers the government message box, one more row lets the
// resident switch letters to it off (inbox-berichtenbox-channel, REQ-MBC-005).
//
// @spec openspec/specs/portal-notifications-and-preferences/spec.md#requirement-the-choices-live-on-the-inbox-page-req-nap-008

import { useEffect, useState } from 'react'
import { messageBoxChoice, withMessageBoxChoice } from '../../shared/messageBox.js'

const KINDS = [
	{ key: 'case.updated', label: 'Changes on your cases' },
	{ key: 'message.created', label: 'New messages' },
]

/**
 * @param {object} root0 Props.
 * @param {object} root0.api The portal API.
 * @param {Function} root0.t Translator.
 * @return {object|null} The settings section, or nothing until the choices load.
 */
export default function NotificationSettings({ api, t }) {
	const [loaded, setLoaded] = useState(null)
	const [choices, setChoices] = useState({})
	const [status, setStatus] = useState('')
	const [busy, setBusy] = useState(false)

	useEffect(() => {
		let alive = true
		api.fetchNotificationPreferences().then((answer) => {
			if (alive && answer) {
				setLoaded(answer)
				setChoices(answer.preferences)
			}
		})
		return () => {
			alive = false
		}
	}, [api])

	if (!loaded) {
		return null
	}

	const channels = loaded.pushAvailable ? ['email', 'push'] : ['email']
	const messageBox = messageBoxChoice(loaded)

	/**
	 * @param {string} kind The kind.
	 * @param {string} channel The channel.
	 * @param {boolean} value On or off.
	 */
	function set(kind, channel, value) {
		setStatus('')
		setChoices((c) => ({
			...c,
			[kind]: { ...(c[kind] || {}), [channel]: value },
		}))
	}

	/**
	 * @param {Event} event The submit.
	 */
	async function save(event) {
		event.preventDefault()
		setBusy(true)
		const saved = await api.saveNotificationPreferences(choices)
		setBusy(false)
		if (saved) {
			setChoices(saved.preferences)
			setStatus(t('Your choices are saved.'))
		} else {
			setStatus(t('Your choices could not be saved. Try again.'))
		}
	}

	return (
		<details className="portaliq-notification-settings">
			<summary>{t('Notification settings')}</summary>
			<form onSubmit={save}>
				<table>
					<thead>
						<tr>
							<th scope="col">
								<span className="portaliq-sr-only">
									{t('Notification settings')}
								</span>
							</th>
							{channels.map((channel) => (
								<th key={channel} scope="col">
									{channel === 'email' ? t('E-mail') : t('Push')}
								</th>
							))}
						</tr>
					</thead>
					<tbody>
						{KINDS.map((kind) => (
							<tr key={kind.key}>
								<th scope="row">{t(kind.label)}</th>
								{channels.map((channel) => {
									const id =
										`portaliq-notify-${kind.key}-${channel}`.replace(
											/\./g,
											'-',
										)
									return (
										<td key={channel}>
											<input
												id={id}
												type="checkbox"
												checked={
													choices[kind.key]?.[channel]
													!== false
												}
												onChange={(e) =>
													set(
														kind.key,
														channel,
														e.target.checked,
													)
												}
											/>
											<label
												htmlFor={id}
												className="portaliq-sr-only">
												{`${t(kind.label)}: ${channel === 'email' ? t('E-mail') : t('Push')}`}
											</label>
										</td>
									)
								})}
							</tr>
						))}
					</tbody>
				</table>
				{messageBox && (
					<p className="portaliq-notification-settings__message-box">
						<input
							id="portaliq-notify-message-box"
							type="checkbox"
							checked={choices.messageBox?.enabled !== false}
							onChange={(e) => {
								setStatus('')
								setChoices((c) =>
									withMessageBoxChoice(c, e.target.checked),
								)
							}}
						/>
						<label htmlFor="portaliq-notify-message-box">
							{t('Also send letters to {label}', {
								label: messageBox.label,
							})}
						</label>
					</p>
				)}
				<button type="submit" disabled={busy}>
					{t('Save')}
				</button>
				{status && <p role="status">{status}</p>}
			</form>
		</details>
	)
}
