// src/site/modals/c/RowActionConfirm.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<template>
	<section
		class="pq-rowaction"
		:aria-label="label"
		data-testid="rowaction-confirm">
		<h3 ref="heading" class="utrecht-heading-3" tabindex="-1">
			{{ label }}
		</h3>
		<p
			v-if="notice !== ''"
			class="utrecht-paragraph pq-rowaction__notice"
			role="status">
			{{ notice }}
		</p>
		<div class="pq-rowaction__buttons">
			<button
				v-if="message === ''"
				type="button"
				class="utrecht-button utrecht-button--primary-action"
				:disabled="busy"
				data-testid="rowaction-continue"
				@click="confirm">
				{{ busy ? translate('Please wait…') : translate('Continue') }}
			</button>
			<button
				type="button"
				class="utrecht-button utrecht-button--subtle"
				:disabled="busy"
				@click="$emit('close')">
				{{ message === '' ? translate('Cancel') : translate('Close') }}
			</button>
		</div>
		<p
			class="utrecht-paragraph pq-rowaction__status"
			role="status"
			data-testid="rowaction-status">
			{{ message }}
		</p>
		<p v-if="link !== ''" class="pq-rowaction__link">
			<label class="utrecht-form-label" :for="`rowaction-link-${action.id}`">{{
				translate('Link')
			}}</label>
			<input
				:id="`rowaction-link-${action.id}`"
				type="text"
				class="utrecht-textbox utrecht-textbox--html-input utrecht-textbox--read-only"
				readonly
				:value="link"
				data-testid="rowaction-link"
				@focus="$event.target.select()" />
			<button
				type="button"
				class="utrecht-button utrecht-button--secondary-action"
				@click="copyLink">
				{{ translate('Copy link') }}
			</button>
		</p>
	</section>
</template>

<script>
import { rowNotice, runRowAction } from '../../../shared/rowAction.js'
import { translatorOr } from '../../components/c/forms.js'

/**
 * The browser navigation, kept apart so a caller or test can pass its own.
 *
 * @param {string} url An absolute https URL, already checked by redirectTarget.
 */
function goTo(url) {
	window.location.assign(url)
}

/**
 * The confirm step of an endpoint row action (the Vue port of
 * RowActionConfirm.jsx). The resident reads what they are about to do and the
 * row's notice before anything is sent. On confirm the row-scoped forward
 * runs, and the browser follows a checked redirect or the answer shows in one
 * line, with any link the action answered.
 *
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-an-endpoint-row-action-must-confirm-before-it-runs-req-srp-026
 */
export default {
	name: 'RowActionConfirm',

	props: {
		/** The resolved endpoint row action. */
		action: { type: Object, required: true },
		/** The collection the row belongs to. */
		collection: { type: Object, required: true },
		/** The row. */
		row: { type: Object, required: true },
		/** The portal api (`forwardRowAction`). */
		api: { type: Object, required: true },
		/** The translator `t(key, vars)`. */
		t: { type: Function, default: null },
		/** Where a checked redirect goes; the browser by default. */
		navigate: { type: Function, default: goTo },
	},

	emits: ['done', 'close'],

	data() {
		return {
			busy: false,
			message: '',
			link: '',
		}
	},

	computed: {
		translate() {
			return translatorOr(this.t)
		},

		label() {
			return this.action.label || this.action.id
		},

		notice() {
			return rowNotice(this.collection, this.row)
		},
	},

	mounted() {
		if (this.$refs.heading) {
			this.$refs.heading.focus()
		}
	},

	methods: {
		/**
		 * Run the forward and handle its answer.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-an-endpoint-row-action-must-confirm-before-it-runs-req-srp-026
		 */
		async confirm() {
			this.busy = true
			const { redirect, messageKey, link } = await runRowAction(
				this.api,
				this.collection,
				this.row,
				this.action,
			)
			if (redirect) {
				this.navigate(redirect)
				return
			}
			this.busy = false
			this.message = this.translate(messageKey)
			this.link = link || ''
			this.$emit('done')
		},

		copyLink() {
			if (typeof navigator !== 'undefined' && navigator.clipboard) {
				navigator.clipboard.writeText(this.link)
			}
		},
	},
}
</script>

<style scoped>
.pq-rowaction {
	margin-block: var(--utrecht-space-block-md, 1rem);
	padding: var(--utrecht-space-block-md, 1rem);
	border: var(--utrecht-border-width-sm, 1px) solid
		var(--utrecht-color-grey-60, currentcolor);
}

.pq-rowaction__buttons {
	display: flex;
	flex-wrap: wrap;
	gap: var(--utrecht-space-inline-sm, 0.5rem);
}

.pq-rowaction__status:empty {
	display: none;
}

.pq-rowaction__link {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	gap: var(--utrecht-space-inline-sm, 0.5rem);
}
</style>

// src/portal/components/RowActionConfirm.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// The confirm step of an endpoint row action (contribution-pay-screen): a
// guardian who pressed "Pay now" on a school contribution reads what they are
// about to do, and the notice the row carries (a voluntary contribution says
// so), before anything is sent. On confirm it runs the row-scoped forward and
// either sends the browser to the checkout the leaf app returned or says, in
// one line, what happened.
//
// No amount, no invoice state and no payment rule lives here: the server reads
// the row under the subject's scope and the leaf app decides the rest.

import { useEffect, useRef, useState } from 'react'
import { rowNotice, runRowAction } from '../../shared/rowAction.js'

/**
 * The browser navigation, kept apart so a test can pass its own.
 *
 * @param {string} url An absolute https URL, already checked by redirectTarget.
 */
function goTo(url) {
	window.location.assign(url)
}

/**
 * Confirm and run one endpoint row action for one row.
 *
 * @param {object} root0 Props.
 * @param {object} root0.action The resolved endpoint row action.
 * @param {object} root0.collection The collection the row belongs to.
 * @param {object} root0.row The row.
 * @param {object} root0.api The portal api (forwardRowAction).
 * @param {(key: string) => string} root0.t The translator.
 * @param {() => void} [root0.onDone] Called after an answer that did not redirect (reload the list).
 * @param {() => void} [root0.onClose] Called when the subject closes the step.
 * @param {(url: string) => void} [root0.navigate] Where a checked redirect goes; defaults to the browser.
 * @return {object} The confirm step.
 */
export default function RowActionConfirm({ action, collection, row, api, t, onDone, onClose, navigate = goTo }) {
	const [busy, setBusy] = useState(false)
	const [message, setMessage] = useState('')
	// A link the action answered with, e.g. a dossier's share link (my-dossiers REQ-MYD-004).
	const [link, setLink] = useState('')
	const headingRef = useRef(null)
	const notice = rowNotice(collection, row)
	const label = action.label || action.id

	// Move focus into the step when it opens, so a keyboard or screen reader
	// user lands on what they are confirming.
	useEffect(() => {
		if (headingRef.current) {
			headingRef.current.focus()
		}
	}, [])

	/**
	 * Run the forward and handle its answer.
	 */
	async function onConfirm() {
		setBusy(true)
		const { redirect, messageKey, link: answered } = await runRowAction(api, collection, row, action)
		if (redirect) {
			navigate(redirect)
			return
		}
		setBusy(false)
		setMessage(t(messageKey))
		setLink(answered || '')
		if (onDone) {
			onDone()
		}
	}

	return (
		<section className="portaliq-rowaction-confirm" aria-label={label}>
			<h4 ref={headingRef} tabIndex={-1}>{label}</h4>
			{notice && <p className="portaliq-notice" role="status">{notice}</p>}
			<div className="portaliq-rowaction-buttons">
				{message === '' && (
					<button type="button" className="portaliq-cta" disabled={busy} onClick={onConfirm}>
						{busy ? t('Please wait…') : t('Continue')}
					</button>
				)}
				<button type="button" disabled={busy} onClick={() => onClose && onClose()}>
					{message === '' ? t('Cancel') : t('Close')}
				</button>
			</div>
			<p className="portaliq-rowaction-status" role="status">{message}</p>
			{link !== '' && (
				<p className="portaliq-rowaction-link">
					<label htmlFor={`rowaction-link-${action.id}`}>{t('Link')}</label>
					<input id={`rowaction-link-${action.id}`} type="text" readOnly value={link} data-testid="rowaction-link" onFocus={(event) => event.target.select()} />
					<button type="button" onClick={() => navigator.clipboard && navigator.clipboard.writeText(link)}>{t('Copy link')}</button>
				</p>
			)}
		</section>
	)
}
