// src/site/pages/inbox/TasksPage.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	"My tasks" (portal-task-delivery): the resident's open portal tasks, read
	and completed through portaliq's bearer-guarded proxy. The completion form
	checks the task's frozen upload rules before sending and names each
	refusal in plain language; the server checks everything again. "View task"
	in the inbox opens one task here directly.
-->
<template>
	<div class="pq-tasks-page">
		<template v-if="detail">
			<BusyStatus v-if="detail.loading" :t="tr" />

			<section v-else-if="detail.refusal" class="pq-task-detail">
				<p class="utrecht-paragraph pq-task-refusal" role="alert">
					{{ tr(detail.refusal) }}
				</p>
				<button
					type="button"
					class="utrecht-button utrecht-button--subtle"
					@click="backToList">
					{{ tr('Back to the list') }}
				</button>
			</section>

			<section v-else class="pq-task-detail">
				<h2 class="utrecht-heading-2">
					{{ detail.task.title || tr('Task') }}
				</h2>
				<p
					v-if="detail.task.description"
					class="utrecht-paragraph pq-task-description">
					{{ detail.task.description }}
				</p>
				<p v-if="due(detail.task)" class="utrecht-paragraph pq-task-due">
					{{ tr('Finish before {date}', { date: due(detail.task) }) }}
					<strong
						v-if="detail.task.overdue === true"
						class="pq-task-overdue">
						· {{ tr('Overdue') }}
					</strong>
				</p>

				<p
					v-if="completed"
					class="utrecht-paragraph pq-task-done"
					role="status">
					{{ tr('Your task has been submitted. Thank you.') }}
				</p>

				<form v-else class="pq-task-form" @submit.prevent="submit">
					<div class="utrecht-form-field pq-task-upload">
						<label class="utrecht-form-label" for="portaliq-task-files">
							{{
								rules.required
									? tr('Add a file (required)')
									: tr('Add a file (optional)')
							}}
						</label>
						<ul
							v-if="ruleLines.length > 0"
							id="portaliq-task-file-rules"
							class="pq-task-upload-rules">
							<li v-for="line in ruleLines" :key="line">
								{{ line }}
							</li>
						</ul>
						<input
							id="portaliq-task-files"
							type="file"
							class="pq-task-file-input"
							:multiple="rules.maxFiles > 1"
							:accept="accept"
							:aria-required="rules.required ? 'true' : undefined"
							:aria-describedby="
								ruleLines.length > 0
									? 'portaliq-task-file-rules'
									: undefined
							"
							@change="pick($event.target.files)" />
					</div>

					<div class="utrecht-form-field pq-task-comment">
						<label
							class="utrecht-form-label"
							for="portaliq-task-comment">
							{{ tr('Comment (optional)') }}
						</label>
						<textarea
							id="portaliq-task-comment"
							v-model="comment"
							class="utrecht-textarea"
							rows="4" />
					</div>

					<p
						v-if="formError"
						class="utrecht-paragraph pq-error"
						role="alert">
						{{ formError }}
					</p>

					<button
						type="submit"
						class="utrecht-button utrecht-button--primary-action"
						:disabled="busy">
						{{ busy ? tr('Sending…') : tr('Submit task') }}
					</button>
				</form>

				<button
					type="button"
					class="utrecht-button utrecht-button--subtle"
					@click="backToList">
					{{ tr('Back to the list') }}
				</button>
			</section>
		</template>

		<BusyStatus v-else-if="loading" :t="tr" />

		<p v-else-if="tasks.length === 0" class="utrecht-paragraph pq-empty">
			<em>{{ tr('No open tasks.') }}</em>
		</p>

		<ul v-else class="pq-tasks">
			<li v-for="task in tasks" :key="task.uuid" class="pq-task-row">
				<button
					type="button"
					class="utrecht-button utrecht-button--subtle pq-task-open"
					@click="openTask(task.uuid)">
					<span class="pq-task-title">{{
						task.displayTitle || task.title
					}}</span>
					<span v-if="task.dueAt" class="pq-task-row-due">
						{{ tr('Finish before {date}', { date: due(task) }) }}
						<strong v-if="task.overdue === true" class="pq-task-overdue">
							· {{ tr('Overdue') }}
						</strong>
					</span>
				</button>
			</li>
		</ul>
	</div>
</template>

<script>
import BusyStatus from '../../components/inbox/BusyStatus.vue'
import { formatDate, sessionStore, takeTaskToOpen } from './inbox.js'
import { PAGE_EMITS, PAGE_PROPS } from './pageProps.js'
import {
	acceptAttribute,
	refusalKey,
	sizeInMb,
	uploadRules,
	validateFiles,
} from './tasks.js'
import { pageLocale, withStrings } from './translate.js'

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
 */
export default {
	name: 'TasksPage',

	components: { BusyStatus },

	props: {
		...PAGE_PROPS,
		/** A task to open on arrival; else the one the inbox left. */
		initialTaskUuid: { type: String, default: '' },
	},

	emits: PAGE_EMITS,

	data() {
		return {
			loading: true,
			tasks: [],
			detail: null,
			comment: '',
			files: [],
			formError: '',
			busy: false,
			completed: false,
		}
	},

	computed: {
		/**
		 * @return {string} `nl` or `en`.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		lang() {
			return pageLocale(this.locale)
		},

		/**
		 * @return {(key: string, vars?: object) => string} The translator.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		tr() {
			return withStrings(this.t, this.lang)
		},

		/**
		 * @return {object} The open task's upload rules.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		rules() {
			return uploadRules(this.detail?.task)
		},

		/**
		 * @return {Array<string>} The rules as sentences under the file field.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		ruleLines() {
			const lines = []
			if (this.rules.maxFiles > 1) {
				lines.push(
					this.tr('You can add at most {count} file(s).', {
						count: this.rules.maxFiles,
					}),
				)
			}
			if (this.rules.maxSizeBytes > 0) {
				lines.push(
					this.tr('Maximum file size: {size} MB.', {
						size: sizeInMb(this.rules.maxSizeBytes),
					}),
				)
			}
			if (this.rules.acceptedTypes.length > 0) {
				lines.push(
					this.tr('Allowed file types: {types}.', {
						types: this.rules.acceptedTypes.join(', '),
					}),
				)
			}
			return lines
		},

		/**
		 * @return {string|undefined} The file input's accept value.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		accept() {
			return acceptAttribute(this.rules.acceptedTypes)
		},
	},

	created() {
		this.loadList()
		const uuid = this.initialTaskUuid || takeTaskToOpen(sessionStore())
		if (uuid) {
			this.openTask(uuid)
		}
	},

	methods: {
		/**
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		async loadList() {
			this.loading = true
			const page = await this.api.fetchTasks()
			this.tasks = Array.isArray(page?.results) ? page.results : []
			this.loading = false
		},

		/**
		 * Open one task, or say why it cannot be opened.
		 *
		 * @param {string} uuid The task uuid.
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		async openTask(uuid) {
			this.comment = ''
			this.files = []
			this.formError = ''
			this.completed = false
			this.detail = { loading: true }
			const res = await this.api.fetchTask(uuid)
			this.detail = res?.ok
				? { task: res.task }
				: { refusal: refusalKey(res?.code) }
		},

		/**
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		backToList() {
			this.detail = null
			this.loadList()
		},

		/**
		 * @param {FileList|Array<File>|null} list The chosen files.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		pick(list) {
			this.files = Array.from(list || [])
			this.formError = ''
		},

		/**
		 * @param {object} task A task row.
		 * @return {string} Its due date in the page language.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		due(task) {
			return formatDate(task?.dueAt, this.lang)
		},

		/**
		 * Check the files, then send the comment and files through the proxy.
		 *
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		async submit() {
			const task = this.detail?.task
			if (!task || this.busy) {
				return
			}
			const violation = validateFiles(task, this.files, this.tr)
			if (violation) {
				this.formError = violation
				return
			}
			this.formError = ''
			this.busy = true
			const res = await this.api.completeTask(task.uuid, {
				comment: this.comment,
				files: this.files,
			})
			this.busy = false
			if (res?.ok) {
				this.completed = true
				this.loadList()
				this.$emit('refresh')
				return
			}
			this.formError = this.tr(refusalKey(res?.code))
		},
	},
}
</script>

<style scoped>
.pq-tasks {
	margin: 0;
	padding: 0;
	list-style: none;
}

.pq-task-open {
	display: flex;
	flex-direction: column;
	align-items: flex-start;
	text-align: start;
}

.pq-task-form {
	display: flex;
	flex-direction: column;
	gap: 16px;
	margin-block: 16px;
}
</style>

// src/portal/components/TasksPage.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// "Mijn taken" (portal-task-delivery): the authenticated party's open portal
// tasks, read and completed through portaliq's bearer-guarded proxy — the
// browser never calls openregister and never holds an X-Portal-Subject
// assertion. The completion form honours the task's frozen upload constraints
// (metadata.upload: required / maxFiles / maxSizeBytes / acceptedTypes)
// client-side, and renders the proxy's named refusals in plain language; the
// server re-checks everything (defense in depth).

import { useCallback, useEffect, useState } from 'react'

/**
 * Format an ISO timestamp as a local date, or '' when absent/invalid.
 *
 * @param value The ISO timestamp.
 * @param locale The resolved locale.
 */
function formatDate(value, locale) {
	if (!value) {
		return ''
	}
	try {
		return new Date(value).toLocaleDateString(
			locale === 'en' ? 'en-GB' : 'nl-NL',
		)
	} catch {
		return String(value)
	}
}

/**
 * The frozen upload constraints of a task row, normalised.
 *
 * @param task The task row.
 */
function uploadRules(task) {
	const upload = (task && task.metadata && task.metadata.upload) || {}
	return {
		required: upload.required === true,
		maxFiles: Number(upload.maxFiles) > 0 ? Number(upload.maxFiles) : 1,
		maxSizeBytes:
			Number(upload.maxSizeBytes) > 0 ? Number(upload.maxSizeBytes) : 0,
		acceptedTypes: Array.isArray(upload.acceptedTypes)
			? upload.acceptedTypes.map(String)
			: [],
	}
}

/**
 * Whether one file matches an accepted-type entry: exact media type, a
 * `type/*` wildcard, or an extension (`pdf` / `.pdf`) — mirrors the server's
 * matcher so a refusal is seen before the upload, not after.
 *
 * @param file The chosen File.
 * @param accepted The accepted-type entries.
 */
function typeAccepted(file, accepted) {
	if (accepted.length === 0) {
		return true
	}
	const type = String(file.type || '').toLowerCase()
	const extension = String(file.name || '')
		.split('.')
		.pop()
		.toLowerCase()
	return accepted.some((entry) => {
		const wanted = String(entry).toLowerCase()
		if (wanted.endsWith('/*')) {
			return type.startsWith(wanted.slice(0, -1))
		}
		if (wanted.includes('/')) {
			return type === wanted
		}
		return extension === wanted.replace(/^\./, '')
	})
}

/**
 * Map the proxy's refusal code to a plain-language message key.
 *
 * @param code The refusal code.
 */
function refusalKey(code) {
	if (code === 'no-such-task') {
		return 'This task does not exist or is not yours.'
	}
	if (code === 'task-closed') {
		return 'This task is already closed.'
	}
	if (code === 'upload-constraint') {
		return 'The upload was refused. Check the file rules above.'
	}
	return 'The tasks are not available right now. Please try again later.'
}

/**
 * The "Mijn taken" page: list, detail and completion form.
 *
 * @param root0 The props.
 * @param root0.api The portal API adapter.
 * @param root0.t The translator.
 * @param root0.locale The resolved locale.
 * @param root0.initialTaskUuid A task uuid to open on mount (the inbox deep link), or null.
 * @param root0.onTaskCompleted Called after a successful completion (lets the shell refresh).
 */
export default function TasksPage({
	api,
	t,
	locale,
	initialTaskUuid = null,
	onTaskCompleted,
}) {
	const [list, setList] = useState({ loading: true, results: [] })
	const [detail, setDetail] = useState(null) // {task} | {refusal} | null (list view)
	const [comment, setComment] = useState('')
	const [files, setFiles] = useState([])
	const [formError, setFormError] = useState(null)
	const [busy, setBusy] = useState(false)
	const [completed, setCompleted] = useState(false)

	const loadList = useCallback(async () => {
		setList((s) => ({ ...s, loading: true }))
		const page = await api.fetchTasks()
		setList({ loading: false, results: page.results })
	}, [api])

	useEffect(() => {
		loadList()
	}, [loadList])

	const openTask = useCallback(
		async (uuid) => {
			setComment('')
			setFiles([])
			setFormError(null)
			setCompleted(false)
			setDetail({ loading: true })
			const res = await api.fetchTask(uuid)
			if (res.ok) {
				setDetail({ task: res.task })
			} else {
				setDetail({ refusal: refusalKey(res.code) })
			}
		},
		[api],
	)

	// The inbox deep link: open the named task once, on arrival.
	useEffect(() => {
		if (initialTaskUuid) {
			openTask(initialTaskUuid)
		}
	}, [initialTaskUuid, openTask])

	/**
	 * Validate the chosen files against the task's frozen rules; returns the
	 * first violated rule as a rendered message, or null when all pass.
	 *
	 * @param task The task row.
	 * @param chosen The chosen File list.
	 */
	function validateFiles(task, chosen) {
		const rules = uploadRules(task)
		if (rules.required && chosen.length === 0) {
			return t('A file is required for this task.')
		}
		if (chosen.length > rules.maxFiles) {
			return t('You can add at most {count} file(s).', {
				count: rules.maxFiles,
			})
		}
		for (const file of chosen) {
			if (rules.maxSizeBytes > 0 && file.size > rules.maxSizeBytes) {
				return t('This file is too large. The limit is {size} MB.', {
					size: Math.round(rules.maxSizeBytes / (1024 * 1024)),
				})
			}
			if (!typeAccepted(file, rules.acceptedTypes)) {
				return t('This file type is not accepted. Allowed: {types}.', {
					types: rules.acceptedTypes.join(', '),
				})
			}
		}
		return null
	}

	/**
	 * Submit the completion through the proxy.
	 *
	 * @param task The open task.
	 */
	async function submit(task) {
		const violation = validateFiles(task, files)
		if (violation) {
			setFormError(violation)
			return
		}
		setFormError(null)
		setBusy(true)
		const res = await api.completeTask(task.uuid, { comment, files })
		setBusy(false)
		if (res.ok) {
			setCompleted(true)
			loadList()
			if (onTaskCompleted) {
				onTaskCompleted()
			}
			return
		}
		setFormError(t(refusalKey(res.code)))
	}

	if (detail) {
		if (detail.loading) {
			return <p className="portaliq-loading">…</p>
		}

		const back = (
			<button
				type="button"
				className="portaliq-tasks-back"
				onClick={() => {
					setDetail(null)
					loadList()
				}}>
				{t('Back to the list')}
			</button>
		)

		if (detail.refusal) {
			return (
				<section className="portaliq-task-detail">
					<p className="portaliq-task-refusal">{t(detail.refusal)}</p>
					{back}
				</section>
			)
		}

		const task = detail.task
		const rules = uploadRules(task)
		const due = formatDate(task.dueAt, locale)

		return (
			<section className="portaliq-task-detail">
				<h1>{task.title || t('Task')}</h1>
				{task.description && (
					<p className="portaliq-task-description">{task.description}</p>
				)}
				{due && (
					<p className="portaliq-task-due">
						{t('Finish before {date}', { date: due })}
						{task.overdue === true && (
							<strong className="portaliq-task-overdue">
								{' '}
								· {t('Overdue')}
							</strong>
						)}
					</p>
				)}

				{completed && (
					<p className="portaliq-task-done" role="status">
						{t('Your task has been submitted. Thank you.')}
					</p>
				)}

				{!completed && (
					<form
						className="portaliq-task-form"
						onSubmit={(event) => {
							event.preventDefault()
							submit(task)
						}}>
						<div className="portaliq-task-upload">
							<label htmlFor="portaliq-task-files">
								{rules.required
									? t('Add a file (required)')
									: t('Add a file (optional)')}
							</label>
							<ul className="portaliq-task-upload-rules">
								{rules.maxFiles > 1 && (
									<li>
										{t('You can add at most {count} file(s).', {
											count: rules.maxFiles,
										})}
									</li>
								)}
								{rules.maxSizeBytes > 0 && (
									<li>
										{t('Maximum file size: {size} MB.', {
											size: Math.round(
												rules.maxSizeBytes / (1024 * 1024),
											),
										})}
									</li>
								)}
								{rules.acceptedTypes.length > 0 && (
									<li>
										{t('Allowed file types: {types}.', {
											types: rules.acceptedTypes.join(', '),
										})}
									</li>
								)}
							</ul>
							<input
								id="portaliq-task-files"
								type="file"
								multiple={rules.maxFiles > 1}
								accept={
									rules.acceptedTypes.length > 0
										? rules.acceptedTypes
												.map((e) =>
													e.includes('/')
														? e
														: `.${e.replace(/^\./, '')}`,
												)
												.join(',')
										: undefined
								}
								onChange={(event) =>
									setFiles(Array.from(event.target.files || []))
								}
							/>
						</div>

						<div className="portaliq-task-comment">
							<label htmlFor="portaliq-task-comment">
								{t('Comment (optional)')}
							</label>
							<textarea
								id="portaliq-task-comment"
								value={comment}
								rows={4}
								onChange={(event) => setComment(event.target.value)}
							/>
						</div>

						{formError && (
							<p className="portaliq-task-error" role="alert">
								{formError}
							</p>
						)}

						<button type="submit" disabled={busy}>
							{busy ? t('Sending…') : t('Submit task')}
						</button>
					</form>
				)}

				{back}
			</section>
		)
	}

	if (list.loading) {
		return <p className="portaliq-loading">…</p>
	}

	if (list.results.length === 0) {
		return (
			<p className="portaliq-empty">
				<em>{t('No open tasks.')}</em>
			</p>
		)
	}

	return (
		<ul className="portaliq-tasks">
			{list.results.map((task) => (
				<li key={task.uuid} className="portaliq-task-row">
					<button
						type="button"
						className="portaliq-task-open"
						onClick={() => openTask(task.uuid)}>
						<span className="portaliq-task-title">
							{task.displayTitle || task.title}
						</span>
						{task.dueAt && (
							<span className="portaliq-task-row-due">
								{t('Finish before {date}', {
									date: formatDate(task.dueAt, locale),
								})}
								{task.overdue === true && (
									<strong className="portaliq-task-overdue">
										{' '}
										· {t('Overdue')}
									</strong>
								)}
							</span>
						)}
					</button>
				</li>
			))}
		</ul>
	)
}
