// src/site/components/WaysIn.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<template>
	<div class="pq-ways-in">
		<section
			v-if="ways.register"
			class="pq-way-in"
			aria-labelledby="pq-way-in-register"
			data-testid="way-in-register">
			<h2 id="pq-way-in-register" class="utrecht-heading-3">
				{{ t('Create an account') }}
			</h2>
			<form @submit.prevent="register">
				<div class="utrecht-form-field">
					<label class="utrecht-form-label" for="pq-register-email">{{
						t('E-mail address')
					}}</label>
					<input
						id="pq-register-email"
						v-model="registration.email"
						class="utrecht-textbox"
						type="email"
						name="email"
						autocomplete="email"
						required />
				</div>
				<div class="utrecht-form-field">
					<label class="utrecht-form-label" for="pq-register-name">{{
						t('Your name')
					}}</label>
					<input
						id="pq-register-name"
						v-model="registration.name"
						class="utrecht-textbox"
						type="text"
						name="name"
						autocomplete="name" />
				</div>
				<!-- A field no person sees or fills; a bot that fills every field fills it. -->
				<div class="pq-way-in__trap">
					<label for="pq-register-website">{{
						t('Leave this field empty')
					}}</label>
					<input
						id="pq-register-website"
						v-model="registration.trap"
						type="text"
						name="website"
						tabindex="-1"
						autocomplete="off" />
				</div>
				<button
					type="submit"
					class="utrecht-button utrecht-button--primary-action"
					:disabled="registration.busy">
					{{
						registration.busy ? t('One moment…') : t('Create an account')
					}}
				</button>
			</form>
			<p
				v-if="registration.outcome"
				class="utrecht-paragraph"
				:role="registration.outcome.role"
				data-testid="way-in-register-result">
				{{ registration.outcome.text }}
			</p>
		</section>

		<section
			v-if="ways.reference"
			class="pq-way-in"
			aria-labelledby="pq-way-in-reference"
			data-testid="way-in-reference">
			<h2 id="pq-way-in-reference" class="utrecht-heading-3">
				{{ t('Follow a case with its case number') }}
			</h2>
			<form @submit.prevent="requestLink">
				<div
					v-if="ways.referenceCaseTypes.length > 1"
					class="utrecht-form-field">
					<label class="utrecht-form-label" for="pq-reference-type">{{
						t('Kind of case')
					}}</label>
					<select
						id="pq-reference-type"
						v-model.number="reference.choice"
						class="utrecht-select">
						<option
							v-for="(type, index) in ways.referenceCaseTypes"
							:key="`${type.register}/${type.schema}/${type.caseType}`"
							:value="index">
							{{ type.label || type.caseType }}
						</option>
					</select>
				</div>
				<div class="utrecht-form-field">
					<label class="utrecht-form-label" for="pq-reference-number">{{
						t('Case number')
					}}</label>
					<input
						id="pq-reference-number"
						v-model="reference.caseReference"
						class="utrecht-textbox"
						type="text"
						name="caseReference"
						autocomplete="off"
						required />
				</div>
				<div class="utrecht-form-field">
					<label class="utrecht-form-label" for="pq-reference-email">{{
						t('E-mail address')
					}}</label>
					<input
						id="pq-reference-email"
						v-model="reference.email"
						class="utrecht-textbox"
						type="email"
						name="email"
						autocomplete="email"
						required />
				</div>
				<button
					type="submit"
					class="utrecht-button utrecht-button--secondary-action"
					:disabled="reference.busy">
					{{ t('Send me a link') }}
				</button>
			</form>
			<p
				v-if="reference.outcome"
				class="utrecht-paragraph"
				:role="reference.outcome.role"
				data-testid="way-in-reference-result">
				{{ reference.outcome.text }}
			</p>
		</section>
	</div>
</template>

<script>
import {
	registrationOutcomeText,
	solveChallenge,
	wayInRefusalText,
	waysInApi,
} from '../lib/waysIn.js'

/**
 * The doors on the site's sign-in screen besides the sign-in buttons
 * (identity-ways-in-screens T02, T04): "Create an account" and "Follow a case
 * with its case number", each only when the site config's `waysIn` opens it.
 *
 * @spec openspec/specs/portal-ways-in/spec.md#requirement-the-sign-in-screen-shows-only-the-doors-that-lead-somewhere-req-iwi-005
 */
export default {
	name: 'WaysIn',

	props: {
		/** The doors, from `waysInFrom()`. */
		ways: { type: Object, required: true },
		/** The portal API base (`.../portal/api`). */
		authBase: { type: String, required: true },
		/** The serving portal's slug, or ''. */
		portal: { type: String, default: '' },
		/** The translator. */
		t: { type: Function, required: true },
	},

	data() {
		return {
			registration: {
				email: '',
				name: '',
				trap: '',
				busy: false,
				outcome: null,
			},

			reference: {
				choice: 0,
				caseReference: '',
				email: '',
				busy: false,
				outcome: null,
			},
		}
	},

	computed: {
		/**
		 * The identity routes for this portal.
		 *
		 * @return {object}
		 */
		api() {
			return waysInApi(this.authBase, this.portal)
		},
	},

	methods: {
		/**
		 * Solve the challenge and register; show the policy's outcome.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/archive/2026-10-02-identity-ways-in-screens/tasks.md#T02
		 */
		async register() {
			this.registration.busy = true
			this.registration.outcome = null
			const challenge = (await this.api.challenge('registration')) || {}
			const solution = challenge.difficulty
				? await solveChallenge(challenge.nonce, challenge.difficulty)
				: ''
			const answer = await this.api.registerAccount({
				email: this.registration.email,
				displayName: this.registration.name,
				challenge,
				solution,
				honeypot: challenge.honeypotField
					? {
							field: challenge.honeypotField,
							value: this.registration.trap,
						}
					: null,
			})
			this.registration.busy = false
			this.registration.outcome = answer.ok
				? {
						role: 'status',
						text: this.t(registrationOutcomeText(answer.data.awaiting)),
					}
				: { role: 'alert', text: this.t(wayInRefusalText(answer.error)) }
		},

		/**
		 * Ask for a reference link. The server answers the same whether or not
		 * the number and the address belong together, so the sentence does too.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/archive/2026-10-02-identity-ways-in-screens/tasks.md#T04
		 */
		async requestLink() {
			const type = this.ways.referenceCaseTypes[this.reference.choice]
			if (!type) {
				return
			}
			this.reference.busy = true
			const answer = await this.api.requestReferenceLink({
				register: type.register,
				schema: type.schema,
				caseType: type.caseType,
				caseReference: this.reference.caseReference,
				email: this.reference.email,
			})
			this.reference.busy = false
			this.reference.outcome = answer.ok
				? {
						role: 'status',
						text: this.t(
							'If the case number and the e-mail address belong together, we sent a link to that address. It works once.',
						),
					}
				: { role: 'alert', text: this.t(wayInRefusalText(answer.error)) }
		},
	},
}
</script>

<style scoped>
.pq-way-in {
	margin-block-start: var(--utrecht-space-block-lg, 2rem);
}

/* Out of sight and out of the tab order; still in the form for a bot. */
.pq-way-in__trap {
	position: absolute;
	inline-size: 1px;
	block-size: 1px;
	overflow: hidden;
	clip-path: inset(50%);
}
</style>

// src/portal/components/WaysIn.jsx
// SPDX-License-Identifier: EUPL-1.2
// Copyright (C) 2026 Conduction B.V.
//
// The ways into the portal for a visitor without an account
// (identity-ways-in-screens): "Create an account", "Follow a case with its
// case number", and what a mailed link opens: an activation, an invitation or
// one case, read only. Each door renders only when the runtime config's
// `waysIn` says it leads somewhere (REQ-IWI-005).

import { useEffect, useState } from 'react'
import { registrationOutcomeText, solveChallenge, wayInRefusalText } from '../lib/waysIn.js'

/**
 * The sentence after a door that ends in an account.
 *
 * @param {Function} t The translator.
 * @param {string} emailSignIn The label of the e-mail sign-in, or ''.
 * @return {string} The text.
 */
function readyText(t, emailSignIn) {
	return emailSignIn
		? t('Your account is ready. Sign in with {provider}.', { provider: emailSignIn })
		: t('Your account is ready. You can sign in now.')
}

/**
 * "Create an account" (REQ-IWI-002): the challenge is solved in the browser,
 * the honeypot rides along empty, and the policy's outcome is shown.
 *
 * @param {object} props Props.
 * @param {object} props.api The portal API adapter.
 * @param {Function} props.t The translator.
 * @param {Function} [props.solve] The proof of work (test seam).
 * @return {object} The element.
 *
 * @spec openspec/changes/archive/2026-10-01-identity-ways-in-screens/tasks.md#T02
 */
export function CreateAccountForm({ api, t, solve = solveChallenge }) {
	const [email, setEmail] = useState('')
	const [name, setName] = useState('')
	const [honeypot, setHoneypot] = useState('')
	const [busy, setBusy] = useState(false)
	const [outcome, setOutcome] = useState(null)

	/**
	 * Send the registration.
	 *
	 * @param {Event} event The submit.
	 */
	async function submit(event) {
		event.preventDefault()
		setBusy(true)
		setOutcome(null)
		const challenge = (await api.challenge('registration')) || {}
		const solution = challenge.difficulty ? await solve(challenge.nonce, challenge.difficulty) : ''
		const answer = await api.registerAccount({
			email,
			displayName: name,
			challenge,
			solution,
			honeypot: challenge.honeypotField ? { field: challenge.honeypotField, value: honeypot } : null,
		})
		setBusy(false)
		setOutcome(answer.ok
			? { role: 'status', text: t(registrationOutcomeText(answer.data?.awaiting)) }
			: { role: 'alert', text: t(wayInRefusalText(answer.error)) })
	}

	return (
		<section className="portaliq-way-in" aria-labelledby="portaliq-way-in-register" data-testid="way-in-register">
			<h2 id="portaliq-way-in-register">{t('Create an account')}</h2>
			<form onSubmit={submit}>
				<label htmlFor="portaliq-register-email">{t('E-mail address')}</label>
				<input id="portaliq-register-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required />
				<label htmlFor="portaliq-register-name">{t('Your name')}</label>
				<input id="portaliq-register-name" type="text" autoComplete="name" value={name} onChange={(event) => setName(event.target.value)} />
				{/* A field no person sees or fills; a bot that fills every field fills it. */}
				<div className="portaliq-way-in__trap" aria-hidden="true">
					<label htmlFor="portaliq-register-website">{t('Leave this field empty')}</label>
					<input id="portaliq-register-website" type="text" tabIndex={-1} autoComplete="off" value={honeypot} onChange={(event) => setHoneypot(event.target.value)} />
				</div>
				<button type="submit" disabled={busy}>{busy ? t('One moment…') : t('Create an account')}</button>
			</form>
			{outcome && (
				<p className={outcome.role === 'alert' ? 'portaliq-error' : 'portaliq-notice'} role={outcome.role} data-testid="way-in-register-result">{outcome.text}</p>
			)}
		</section>
	)
}

/**
 * "Follow a case with its case number" (REQ-IWI-003): the case types listed
 * are exactly the portal's that admit the reference kind.
 *
 * @param {object} props Props.
 * @param {object} props.api The portal API adapter.
 * @param {Function} props.t The translator.
 * @param {Array<object>} props.caseTypes `{ register, schema, caseType, label }` per case type.
 * @return {object} The element.
 *
 * @spec openspec/changes/archive/2026-10-01-identity-ways-in-screens/tasks.md#T04
 */
export function ReferenceLinkForm({ api, t, caseTypes }) {
	const [choice, setChoice] = useState(0)
	const [caseReference, setCaseReference] = useState('')
	const [email, setEmail] = useState('')
	const [busy, setBusy] = useState(false)
	const [outcome, setOutcome] = useState(null)

	/**
	 * Ask for the link.
	 *
	 * @param {Event} event The submit.
	 */
	async function submit(event) {
		event.preventDefault()
		const type = caseTypes[choice]
		if (!type) {
			return
		}
		setBusy(true)
		const answer = await api.requestReferenceLink({ ...type, caseReference, email })
		setBusy(false)
		// The server answers the same whether or not the number and the
		// address belong together, so the sentence does too.
		setOutcome(answer.ok
			? { role: 'status', text: t('If the case number and the e-mail address belong together, we sent a link to that address. It works once.') }
			: { role: 'alert', text: t(wayInRefusalText(answer.error)) })
	}

	return (
		<section className="portaliq-way-in" aria-labelledby="portaliq-way-in-reference" data-testid="way-in-reference">
			<h2 id="portaliq-way-in-reference">{t('Follow a case with its case number')}</h2>
			<form onSubmit={submit}>
				{caseTypes.length > 1 && (
					<>
						<label htmlFor="portaliq-reference-type">{t('Kind of case')}</label>
						<select id="portaliq-reference-type" value={choice} onChange={(event) => setChoice(Number(event.target.value))}>
							{caseTypes.map((type, index) => (
								<option key={`${type.register}/${type.schema}/${type.caseType}`} value={index}>{type.label}</option>
							))}
						</select>
					</>
				)}
				<label htmlFor="portaliq-reference-number">{t('Case number')}</label>
				<input id="portaliq-reference-number" type="text" value={caseReference} onChange={(event) => setCaseReference(event.target.value)} required />
				<label htmlFor="portaliq-reference-email">{t('E-mail address')}</label>
				<input id="portaliq-reference-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required />
				<button type="submit" disabled={busy}>{t('Send me a link')}</button>
			</form>
			{outcome && (
				<p className={outcome.role === 'alert' ? 'portaliq-error' : 'portaliq-notice'} role={outcome.role} data-testid="way-in-reference-result">{outcome.text}</p>
			)}
		</section>
	)
}

/**
 * One case opened with a reference link: its fields as the case app
 * declared them, and no way to change anything (REQ-IWI-003).
 *
 * @param {object} props Props.
 * @param {Function} props.t The translator.
 * @param {string} props.caseReference The case number.
 * @param {object} props.record The case, projected by the case app.
 * @return {object} The element.
 *
 * @spec openspec/changes/archive/2026-10-01-identity-ways-in-screens/tasks.md#T05
 */
export function ReferenceCaseView({ t, caseReference, record }) {
	const entries = Object.entries(record || {}).filter(([key]) => !key.startsWith('@') && !key.startsWith('_') && key !== 'id' && key !== 'uuid')
	return (
		<section className="portaliq-reference-case" aria-labelledby="portaliq-reference-case-title" data-testid="reference-case">
			<h2 id="portaliq-reference-case-title">{t('Case {reference}', { reference: caseReference })}</h2>
			<p className="portaliq-notice">{t('You are viewing this case with a link. You cannot change anything here.')}</p>
			<dl>
				{entries.map(([key, value]) => (
					<div key={key}>
						<dt>{key}</dt>
						<dd>
							{Array.isArray(value)
								? (
									<ul>
										{value.map((item, index) => (
											<li key={index}>{typeof item === 'object' && item !== null ? Object.values(item).filter((part) => typeof part !== 'object').join(' · ') : String(item)}</li>
										))}
									</ul>
								)
								: String(typeof value === 'object' && value !== null ? JSON.stringify(value) : (value ?? ''))}
						</dd>
					</div>
				))}
			</dl>
		</section>
	)
}

/**
 * What a mailed link opens: an activation, an invitation, or one case.
 *
 * @param {object} props Props.
 * @param {object} props.api The portal API adapter.
 * @param {Function} props.t The translator.
 * @param {{kind: string, token: string}} props.link The consumed fragment.
 * @param {string} props.emailSignIn The label of the e-mail sign-in, or ''.
 * @param {string} props.portalName The portal's name, for the invitation.
 * @return {object} The element.
 *
 * @spec openspec/changes/archive/2026-10-01-identity-ways-in-screens/tasks.md#T06
 */
export function WayInLink({ api, t, link, emailSignIn, portalName }) {
	const [result, setResult] = useState(null)
	const [opened, setOpened] = useState(null)

	useEffect(() => {
		let gone = false
		if (link.kind === 'activate') {
			api.activateAccount(link.token).then((answer) => {
				if (!gone) {
					setResult(answer.ok ? { role: 'status', text: readyText(t, emailSignIn) } : { role: 'alert', text: t(wayInRefusalText(answer.error || 'activation_not_valid')) })
				}
			})
		}
		if (link.kind === 'reference') {
			api.redeemReferenceLink(link.token).then(async (answer) => {
				const read = answer.ok && answer.data?.bearer ? await api.referenceCase(answer.data.bearer) : null
				if (gone) {
					return
				}
				if (read?.case) {
					setOpened({ caseReference: read.caseReference || answer.data.caseReference, record: read.case })
				} else {
					setResult({ role: 'alert', text: t('This link is no longer valid.') })
				}
			})
		}
		return () => {
			gone = true
		}
	}, [api, link, emailSignIn, t])

	/**
	 * Accept the invitation.
	 */
	async function accept() {
		const answer = await api.acceptInvitation(link.token)
		setResult(answer.ok ? { role: 'status', text: readyText(t, emailSignIn) } : { role: 'alert', text: t(wayInRefusalText(answer.error || 'invitation_not_valid')) })
	}

	if (opened) {
		return <ReferenceCaseView t={t} caseReference={opened.caseReference} record={opened.record} />
	}

	return (
		<section className="portaliq-way-in" data-testid={`way-in-link-${link.kind}`}>
			{link.kind === 'invitation' && !result && (
				<>
					<h2>{t('You are invited to {portal}', { portal: portalName })}</h2>
					<button type="button" onClick={accept}>{t('Accept')}</button>
				</>
			)}
			{result && (
				<p className={result.role === 'alert' ? 'portaliq-error' : 'portaliq-notice'} role={result.role} data-testid="way-in-link-result">{result.text}</p>
			)}
		</section>
	)
}
