// src/portal/components/TimelineList.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// The history of one object, as its contributing app declared it through a
// collection's `timeline` (portaliq#723): dossiq's "Wat er is gebeurd" on a
// resident's case. The entries arrive exactly as the app returned them; the
// app decided what is public, so nothing here filters or adds. This only
// orders them newest first and says so when there are none.

/**
 * The moment of an entry, for sorting; entries without one sort last.
 *
 * @param {object} entry A timeline entry.
 * @return {number} Milliseconds since the epoch, or -Infinity.
 */
function momentOf(entry) {
	const time = Date.parse(entry?.occurredAt || entry?.date || '')
	return Number.isNaN(time) ? -Infinity : time
}

/**
 * The entries newest first, without changing the list it was given.
 *
 * @param {Array<object>} entries The entries as returned.
 * @return {Array<object>} A newest-first copy.
 */
export function newestFirst(entries) {
	return (Array.isArray(entries) ? entries : [])
		.map((entry, index) => ({ entry, index }))
		.sort((a, b) => (momentOf(b.entry) - momentOf(a.entry)) || (a.index - b.index))
		.map(({ entry }) => entry)
}

/**
 * The words of one entry: its message, else its label or title.
 *
 * @param {object} entry A timeline entry.
 * @return {string} What happened.
 */
function textOf(entry) {
	return String(entry?.message || entry?.label || entry?.title || '')
}

/**
 * Render one object's declared history.
 *
 * @param {object} root0 The props.
 * @param {string} [root0.label] The heading the app declared.
 * @param {Array<object>|null} root0.entries The entries, or null while loading.
 * @return {object} The rendered history.
 */
export default function TimelineList({ label, entries }) {
	const heading = label || 'Wat er is gebeurd'
	if (entries === null || entries === undefined) {
		return (
			<section className="portaliq-timeline" aria-busy="true">
				<h4>{heading}</h4>
				<p className="portaliq-loading">…</p>
			</section>
		)
	}
	const ordered = newestFirst(entries)
	return (
		<section className="portaliq-timeline">
			<h4>{heading}</h4>
			{ordered.length === 0
				? <p className="portaliq-empty"><em>Er is nog niets gebeurd.</em></p>
				: (
					<ol>
						{ordered.map((entry, i) => {
							const moment = momentOf(entry)
							return (
								<li key={entry.id || i}>
									{moment !== -Infinity && <time dateTime={entry.occurredAt || entry.date}>{new Date(moment).toLocaleDateString('nl-NL')}</time>}
									{moment !== -Infinity && ' '}
									<span>{textOf(entry)}</span>
								</li>
							)
						})}
					</ol>
				)}
		</section>
	)
}

// src/site/components/collections/TimelineList.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<template>
	<section
		class="pq-timeline"
		:aria-busy="entries === null ? 'true' : undefined"
		data-testid="timeline-list">
		<h3 class="utrecht-heading-4">
			{{ heading }}
		</h3>
		<p v-if="entries === null" class="utrecht-paragraph" role="status">
			{{ t('Loading…') }}
		</p>
		<p
			v-else-if="ordered.length === 0"
			class="utrecht-paragraph pq-timeline__empty">
			<em>{{ t('Nothing has happened yet.') }}</em>
		</p>
		<ol v-else class="utrecht-ordered-list pq-timeline__list">
			<li
				v-for="(entry, index) in ordered"
				:key="entry.id || index"
				class="utrecht-ordered-list__item"
				data-testid="timeline-entry">
				<time
					v-if="hasMoment(entry)"
					class="pq-timeline__moment"
					:datetime="entry.occurredAt || entry.date"
					>{{ dateOf(entry) }}</time
				>
				<span>{{ textOf(entry) }}</span>
			</li>
		</ol>
	</section>
</template>

<script>
import { momentOf, newestFirst, textOf } from './timeline.js'

/**
 * The history of one record as its contributing app returned it (slice b,
 * b6): every entry, newest first, under the label the app declared.
 *
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-records-timeline-must-show-as-its-app-returned-it-req-srp-019
 */
export default {
	name: 'TimelineList',

	props: {
		/** The heading the app declared. */
		label: { type: String, default: '' },
		/** The entries, or null while they load. */
		entries: { type: Array, default: null },
		/** The translator. */
		t: { type: Function, required: true },
		/** The language. */
		locale: { type: String, default: 'nl' },
	},

	computed: {
		heading() {
			return this.label || this.t('What happened')
		},

		ordered() {
			return newestFirst(this.entries)
		},
	},

	methods: {
		textOf,
		hasMoment(entry) {
			return momentOf(entry) !== -Infinity
		},

		dateOf(entry) {
			try {
				return new Date(momentOf(entry)).toLocaleDateString(this.locale)
			} catch {
				return String(entry.occurredAt || entry.date)
			}
		},
	},
}
</script>

<style scoped>
.pq-timeline__moment {
	margin-inline-end: var(--utrecht-space-inline-sm, 0.5rem);
}
</style>
