// src/portal/components/InboxPage.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// Unified inbox page (portal-inbox-v2 T05/T06). Renders the aggregated,
// provenance-tagged inbox from `GET /portal/api/inbox` — merged across every
// `kind: inbox` collection the subject's contributions declared, sorted
// newest-first. Each row shows an unread indicator + read-state toggle
// (`PATCH .../inbox/{register}/{schema}/{id}/read`, tamper-proof server-side)
// and, when the contributing app supplied them, the optional WMEBV art 2:10
// readiness fields (nature/rechtsgevolg/term) — absent fields render nothing,
// never an empty placeholder.

import React, { useCallback, useEffect, useState } from 'react'
import { deliveryLine } from '../../shared/messageBox.js'
import Loading from './Loading.jsx'
import NotificationSettings from './NotificationSettings.jsx'
import TranslatedText from './TranslatedText.jsx'

/**
 *
 * @param value
 * @param locale
 */
function formatDateTime(value, locale) {
	if (!value) {
		return ''
	}
	try {
		return new Date(value).toLocaleString(locale === 'en' ? 'en-GB' : 'nl-NL')
	} catch (e) {
		return String(value)
	}
}

/**
 *
 * @param root0
 * @param root0.api
 * @param root0.t
 * @param root0.locale
 * @param root0.onRead
 * @param root0.onOpenTask
 * @param {Function} root0.onOpenRecord Opens the record a message is about (REQ-NAP-005).
 */
export default function InboxPage({ api, t, locale, onRead, onOpenTask, onOpenRecord }) {
	const [state, setState] = useState({ loading: true, messages: [] })
	const [busyId, setBusyId] = useState(null)

	const load = useCallback(async () => {
		setState((s) => ({ ...s, loading: true }))
		const messages = await api.fetchInbox()
		setState({ loading: false, messages })
	}, [api])

	useEffect(() => { load() }, [load])

	/**
	 *
	 * @param message
	 */
	async function onToggleRead(message) {
		const id = message.id || message['@self']?.id
		if (!id || message.read === true) {
			return
		}
		setBusyId(id)
		const result = await api.markMessageRead(message)
		setBusyId(null)
		if (result.ok) {
			// Optimistic, server-confirmed: only flip `read` on this row —
			// mirrors exactly what the server is guaranteed to have changed.
			setState((s) => ({
				...s,
				messages: s.messages.map((m) => ((m.id || m['@self']?.id) === id ? { ...m, read: true } : m)),
			}))
			// Tell the shell one message is no longer unread, so the cross-app
			// Inbox nav badge (portal-inbox-v2 T04) drops in lockstep.
			if (onRead) {
				onRead()
			}
		}
	}

	if (state.loading) {
		return <Loading t={t} />
	}

	// The resident's notice choices sit at the top of the inbox
	// (inbox-notifications-and-preferences, REQ-NAP-008), also when it is empty.
	const settings = <NotificationSettings api={api} t={t} />

	if (state.messages.length === 0) {
		return (
			<>
				{settings}
				<p className="portaliq-empty"><em>{t('No messages.')}</em></p>
			</>
		)
	}

	return (
		<>
			{settings}
			<ul className="portaliq-inbox">
			{state.messages.map((message, i) => {
				const id = message.id || message['@self']?.id || i
				const unread = message.read !== true
				const source = message._source || {}
				return (
					<li key={id} className={unread ? 'portaliq-inbox-row portaliq-inbox-row--unread' : 'portaliq-inbox-row'}>
						<div className="portaliq-inbox-row__header">
							{unread && <span className="portaliq-badge-unread" aria-label={t('Unread')}>●</span>}
							<span className="portaliq-inbox-row__subject">{message.subject || ''}</span>
							{source.label && <span className="portaliq-inbox-row__source">{source.label}</span>}
							<span className="portaliq-inbox-row__date">{formatDateTime(message.receivedAt, locale)}</span>
						</div>

						{message.body && (
							<TranslatedText
								text={message.body}
								translation={message.translation}
								t={t}
								locale={locale}
								id={id}
								bodyClassName="portaliq-inbox-row__body"
							/>
						)}

						{(message.nature || message.rechtsgevolg || message.term) && (
							<dl className="portaliq-inbox-row__meta">
								{message.nature && (
									<div className="portaliq-inbox-row__meta-item">
										<dt>{t('Nature')}</dt>
										<dd>{message.nature}</dd>
									</div>
								)}
								{message.rechtsgevolg && (
									<div className="portaliq-inbox-row__meta-item">
										<dt>{t('Legal effect')}</dt>
										<dd>{message.rechtsgevolg}</dd>
									</div>
								)}
								{message.term && (
									<div className="portaliq-inbox-row__meta-item">
										<dt>{t('Deadline')}</dt>
										<dd>{formatDateTime(message.term, locale)}</dd>
									</div>
								)}
							</dl>
						)}

						{deliveryLine(message, t) && (
							<p className="portaliq-inbox-row__delivery">{deliveryLine(message, t)}</p>
						)}

						{message.recordLink?.id && onOpenRecord && (
							<button
								type="button"
								className="portaliq-inbox-row__task-link"
								onClick={() => onOpenRecord(message.recordLink)}
							>
								{t('Open')}
							</button>
						)}

						{message.taskUuid && onOpenTask && (
							<button
								type="button"
								className="portaliq-inbox-row__task-link"
								onClick={() => onOpenTask(message.taskUuid)}
							>
								{t('View task')}
							</button>
						)}

						<button
							type="button"
							className="portaliq-inbox-row__toggle"
							disabled={!unread || busyId === id}
							onClick={() => onToggleRead(message)}
						>
							{unread ? t('Mark as read') : t('Read')}
						</button>
					</li>
				)
			})}
			</ul>
		</>
	)
}

// src/site/pages/inbox/InboxPage.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	The unified inbox (portal-inbox-v2): every app's messages for this
	resident, merged and newest first. Each row has an unread mark in text,
	a "mark as read" button, the optional readiness fields (nature, legal
	effect, deadline), the message box delivery line, "Open" for the record a
	message is about and "View task" for a task it asks for. The notice choices
	sit at the top, also when the inbox is empty.
-->
<template>
	<div class="pq-inbox-page">
		<BusyStatus v-if="loading" :t="tr" />
		<template v-else>
			<NotificationSettings :api="api" :t="tr" />
			<p v-if="messages.length === 0" class="utrecht-paragraph pq-empty">
				<em>{{ tr('No messages.') }}</em>
			</p>
			<ul v-else class="pq-inbox">
				<li
					v-for="(message, i) in messages"
					:key="idOf(message, i)"
					class="pq-inbox-row"
					:class="{ 'pq-inbox-row--unread': message.read !== true }">
					<div class="pq-inbox-row__header">
						<strong
							v-if="message.read !== true"
							class="pq-inbox-row__unread">
							{{ tr('Unread') }}
						</strong>
						<span class="pq-inbox-row__subject">{{
							message.subject || ''
						}}</span>
						<span
							v-if="message._source?.label"
							class="pq-inbox-row__source">
							{{ message._source.label }}
						</span>
						<span class="pq-inbox-row__date">
							{{ dateTime(message.receivedAt) }}
						</span>
					</div>

					<TranslatedText
						v-if="message.body"
						:id="idOf(message, i)"
						:text="message.body"
						:translation="message.translation || null"
						:t="tr"
						:locale="lang"
						bodyClass="utrecht-paragraph pq-inbox-row__body" />

					<dl v-if="readiness(message)" class="pq-inbox-row__meta">
						<div v-if="message.nature">
							<dt>{{ tr('Nature') }}</dt>
							<dd>{{ message.nature }}</dd>
						</div>
						<div v-if="message.rechtsgevolg">
							<dt>{{ tr('Legal effect') }}</dt>
							<dd>{{ message.rechtsgevolg }}</dd>
						</div>
						<div v-if="message.term">
							<dt>{{ tr('Deadline') }}</dt>
							<dd>{{ dateTime(message.term) }}</dd>
						</div>
					</dl>

					<p
						v-if="delivery(message)"
						class="utrecht-paragraph pq-inbox-row__delivery">
						{{ delivery(message) }}
					</p>

					<div class="pq-inbox-row__actions">
						<button
							v-if="
								message.recordLink?.id && routeOf(message.recordLink)
							"
							type="button"
							class="utrecht-button utrecht-button--secondary-action"
							@click="openRecord(message.recordLink)">
							{{ tr('Open') }}
						</button>
						<button
							v-if="message.taskUuid"
							type="button"
							class="utrecht-button utrecht-button--secondary-action"
							@click="openTask(message.taskUuid)">
							{{ tr('View task') }}
						</button>
						<button
							type="button"
							class="utrecht-button utrecht-button--subtle"
							:disabled="
								message.read === true || busyId === idOf(message, i)
							"
							@click="markRead(message)">
							{{
								message.read === true
									? tr('Read')
									: tr('Mark as read')
							}}
						</button>
					</div>
				</li>
			</ul>
		</template>
	</div>
</template>

<script>
import BusyStatus from '../../components/inbox/BusyStatus.vue'
import NotificationSettings from '../../components/inbox/NotificationSettings.vue'
import TranslatedText from '../../components/inbox/TranslatedText.vue'
import { deliveryLine } from '../../../shared/messageBox.js'
import {
	formatDateTime,
	hasReadiness,
	keepRecordToOpen,
	keepTaskToOpen,
	markedRead,
	recordRoute,
	rowId,
	sessionStore,
	TASKS_ROUTE,
	unreadAfterRead,
} from './inbox.js'
import { PAGE_EMITS, PAGE_PROPS } from './pageProps.js'
import { pageLocale, withStrings } from './translate.js'

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
 */
export default {
	name: 'InboxPage',

	components: { BusyStatus, NotificationSettings, TranslatedText },

	props: PAGE_PROPS,

	emits: PAGE_EMITS,

	data() {
		return {
			loading: true,
			messages: [],
			busyId: null,
			unread: this.contributions?.unreadCount ?? null,
		}
	},

	computed: {
		/**
		 * @return {string} `nl` or `en`.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		lang() {
			return pageLocale(this.locale)
		},

		/**
		 * @return {(key: string, vars?: object) => string} The translator.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		tr() {
			return withStrings(this.t, this.lang)
		},
	},

	created() {
		this.load()
	},

	methods: {
		/**
		 * Read the merged inbox.
		 *
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		async load() {
			this.loading = true
			const messages = await this.api.fetchInbox()
			this.messages = Array.isArray(messages) ? messages : []
			this.loading = false
		},

		/**
		 * @param {object} message A message.
		 * @param {number} i Its position.
		 * @return {string|number} Its id.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		idOf(message, i) {
			return rowId(message, i)
		},

		/**
		 * @param {string} value An ISO date-time.
		 * @return {string} The value in the page language.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		dateTime(value) {
			return formatDateTime(value, this.lang)
		},

		/**
		 * @param {object} message A message.
		 * @return {boolean} Whether it carries readiness fields.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		readiness(message) {
			return hasReadiness(message)
		},

		/**
		 * @param {object} message A message.
		 * @return {string|null} The message box delivery line.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		delivery(message) {
			return deliveryLine(message, this.tr)
		},

		/**
		 * @param {object} link A record link.
		 * @return {string|null} The route of the page that shows it.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		routeOf(link) {
			return recordRoute(this.nav, link)
		},

		/**
		 * Mark one message read; the server confirms, then the row and the
		 * menu's unread count follow.
		 *
		 * @param {object} message The message.
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		async markRead(message) {
			const id = rowId(message)
			if (!id || message.read === true) {
				return
			}
			this.busyId = id
			const result = await this.api.markMessageRead(message)
			this.busyId = null
			if (result?.ok) {
				this.messages = markedRead(this.messages, id)
				this.unread = unreadAfterRead(this.unread)
				this.$emit('unread', this.unread)
			}
		},

		/**
		 * Open the record a message is about, as a link from the e-mail does.
		 *
		 * @param {{app: string, collection: string, id: string}} link The record link.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		openRecord(link) {
			const route = recordRoute(this.nav, link)
			if (!route) {
				return
			}
			keepRecordToOpen(sessionStore(), link)
			this.go('contribution', { open: link }, route)
		},

		/**
		 * Open "My tasks" on the task a message asks for.
		 *
		 * @param {string} uuid The task uuid.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-resident-must-be-able-to-complete-their-tasks-req-srp-035
		 */
		openTask(uuid) {
			keepTaskToOpen(sessionStore(), uuid)
			this.go('tasks', { task: uuid }, TASKS_ROUTE)
		},

		/**
		 * Go elsewhere in the signed-in area.
		 *
		 * @param {string} key The page key.
		 * @param {object} params What the page needs.
		 * @param {string} route The in-site route.
		 * @return {void}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-the-inbox-must-merge-every-apps-messages-req-srp-030
		 */
		go(key, params, route) {
			if (typeof this.navigate === 'function') {
				this.navigate(key, params)
				return
			}
			this.$emit('navigate', route)
		},
	},
}
</script>

<style scoped>
.pq-inbox {
	margin: 0;
	padding: 0;
	list-style: none;
}

.pq-inbox-row {
	padding-block: 12px;
	border-block-end: 1px solid var(--utrecht-color-grey-80, currentcolor);
}

.pq-inbox-row__header {
	display: flex;
	flex-wrap: wrap;
	gap: 8px;
	align-items: baseline;
}

.pq-inbox-row--unread .pq-inbox-row__subject {
	font-weight: bold;
}

.pq-inbox-row__actions {
	display: flex;
	flex-wrap: wrap;
	gap: 8px;
}

.pq-inbox-row__meta div {
	display: flex;
	gap: 8px;
}

.pq-inbox-row__meta dd {
	margin: 0;
}
</style>
