// src/portal/components/MessagesPage.jsx
// SPDX-License-Identifier: EUPL-1.2
// Copyright (C) 2026 Conduction B.V.
//
// A guardian's conversations with school (guardian-direct-messages), read-only,
// in the language the guardian picks (translated-message-notice). The language
// picker writes the account's own `messageLanguage`; messages the server
// translated carry `translation` and render through TranslatedText, which shows
// the AI notice and the original one click away.

import { useCallback, useEffect, useState } from 'react'
import TranslatedText, { languageLabel } from './TranslatedText.jsx'

/**
 * The languages a guardian can pick: the ones hermiq writes a disclosure
 * sentence for. Order: Dutch and English first, then the rest.
 */
export const MESSAGE_LANGUAGES = ['nl', 'en', 'ar', 'tr', 'pl', 'uk', 'de', 'fr', 'es', 'it', 'pt', 'ro', 'bg', 'ru', 'fa', 'zh']

/**
 * A picker label: the language in the portal's language, plus its own name
 * when that differs, so a reader who does not read the portal's language
 * still finds theirs.
 *
 * @param {string} tag The language tag.
 * @param {string} locale The portal's locale.
 * @return {string} For example "Arabic (العربية)".
 */
export function pickerLabel(tag, locale) {
	const inPortal = languageLabel(tag, locale)
	const own = languageLabel(tag, tag)
	return own && own !== inPortal ? `${inPortal} (${own})` : inPortal
}

/**
 * @param {string} value An ISO date-time.
 * @param {string} locale The portal's locale.
 * @return {string}
 */
function formatDateTime(value, locale) {
	if (!value) {
		return ''
	}
	try {
		return new Date(value).toLocaleString(locale === 'en' ? 'en-GB' : 'nl-NL')
	} catch {
		return String(value)
	}
}

/**
 * @param {object} props The props.
 * @param {object} props.api The portal API adapter.
 * @param {(key: string, vars?: object) => string} props.t The portal translator.
 * @param {string} props.locale The portal's locale.
 * @param {string} props.subjectRef The reader's own subjectRef.
 */
export default function MessagesPage({ api, t, locale, subjectRef }) {
	const [threads, setThreads] = useState(null)
	const [activeId, setActiveId] = useState(null)
	const [messages, setMessages] = useState(null)
	const [language, setLanguage] = useState('')
	const [error, setError] = useState('')

	useEffect(() => {
		let live = true
		;(async () => {
			const [list, details] = await Promise.all([api.fetchThreads(), api.getDetails()])
			if (!live) {
				return
			}
			setThreads(list)
			setLanguage(details?.messageLanguage || '')
			if (list.length > 0) {
				setActiveId(list[0].id || list[0]['@self']?.id || null)
			}
		})()
		return () => { live = false }
	}, [api])

	const loadMessages = useCallback(async (threadId) => {
		if (!threadId) {
			return
		}
		setMessages(null)
		setMessages((await api.fetchThreadMessages(threadId)) || [])
	}, [api])

	useEffect(() => { loadMessages(activeId) }, [activeId, loadMessages])

	/**
	 * @param {Event} event The change event of the picker.
	 */
	async function onLanguageChange(event) {
		const next = event.target.value
		setError('')
		const result = await api.setMessageLanguage(next)
		if (!result.ok) {
			setError(t('Your language choice could not be saved.'))
			return
		}
		setLanguage(next)
		loadMessages(activeId)
	}

	if (threads === null) {
		return <p className="portaliq-loading">…</p>
	}

	return (
		<section className="portaliq-messages">
			<div className="portaliq-messages__language">
				<label htmlFor="portaliq-message-language">{t('Show messages in')}</label>
				<select id="portaliq-message-language" value={language} onChange={onLanguageChange}>
					<option value="">{t('As written')}</option>
					{MESSAGE_LANGUAGES.map((tag) => (
						<option key={tag} value={tag}>{pickerLabel(tag, locale)}</option>
					))}
				</select>
				<p className="portaliq-messages__hint">
					{t('Messages from school are translated by AI into this language. You can always see the original text.')}
				</p>
				{error && <p className="portaliq-error" role="alert">{error}</p>}
			</div>

			{threads.length === 0 && <p className="portaliq-empty"><em>{t('No conversations yet.')}</em></p>}

			{threads.length > 0 && (
				<nav className="portaliq-messages__threads" aria-label={t('Conversations')}>
					<ul>
						{threads.map((thread) => {
							const id = thread.id || thread['@self']?.id
							return (
								<li key={id}>
									<button
										type="button"
										aria-current={id === activeId ? 'true' : undefined}
										onClick={() => setActiveId(id)}
									>
										{thread.kind === 'group' ? t('Group conversation') : t('Conversation with school')}
										{' · '}
										{formatDateTime(thread.createdAt, locale)}
									</button>
								</li>
							)
						})}
					</ul>
				</nav>
			)}

			{activeId && messages === null && <p className="portaliq-loading">…</p>}

			{messages && (
				<ol className="portaliq-messages__list">
					{messages.map((message, i) => {
						const id = message.id || message['@self']?.id || i
						const own = message.senderRef === subjectRef
						return (
							<li key={id} className={own ? 'portaliq-message portaliq-message--own' : 'portaliq-message'}>
								<div className="portaliq-message__header">
									<span className="portaliq-message__sender">{own ? t('You') : t('School')}</span>
									<span className="portaliq-message__date">{formatDateTime(message.sentAt, locale)}</span>
								</div>
								<TranslatedText text={message.body || ''} translation={message.translation} t={t} locale={locale} id={id} />
							</li>
						)
					})}
				</ol>
			)}
		</section>
	)
}

// src/site/pages/inbox/MessagesPage.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	A guardian's conversations with school (guardian-direct-messages), read
	only, in the language the guardian picks (translated-message-notice). The
	picker writes the account's own `messageLanguage`; a message the server
	translated shows through TranslatedText, with the AI notice and the
	original one click away.
-->
<template>
	<section class="pq-messages">
		<BusyStatus v-if="threads === null" :t="tr" />
		<template v-else>
			<MessageLanguagePicker
				id="portaliq-message-language"
				:label="tr('Show messages in')"
				:hint="
					tr(
						'Messages from school are translated by AI into this language. You can always see the original text.',
					)
				"
				:language="language"
				:error="error"
				:t="tr"
				:locale="lang"
				@change="changeLanguage" />

			<p v-if="threads.length === 0" class="utrecht-paragraph pq-empty">
				<em>{{ tr('No conversations yet.') }}</em>
			</p>

			<nav
				v-else
				class="pq-messages__threads"
				:aria-label="tr('Conversations')">
				<ul>
					<li v-for="thread in threads" :key="idOf(thread)">
						<button
							type="button"
							class="utrecht-button utrecht-button--subtle"
							:aria-current="
								idOf(thread) === activeId ? 'true' : undefined
							"
							@click="choose(idOf(thread))">
							{{
								thread.kind === 'group'
									? tr('Group conversation')
									: tr('Conversation with school')
							}}
							· {{ dateTime(thread.createdAt) }}
						</button>
					</li>
				</ul>
			</nav>

			<BusyStatus v-if="activeId && messages === null" :t="tr" />

			<ol v-if="messages" class="pq-messages__list">
				<li
					v-for="(message, i) in messages"
					:key="idOf(message, i)"
					class="pq-message"
					:class="{ 'pq-message--own': isOwn(message) }">
					<div class="pq-message__header">
						<strong class="pq-message__sender">
							{{ isOwn(message) ? tr('You') : tr('School') }}
						</strong>
						<span class="pq-message__date">{{
							dateTime(message.sentAt)
						}}</span>
					</div>
					<TranslatedText
						:id="idOf(message, i)"
						:text="message.body || ''"
						:translation="message.translation || null"
						:t="tr"
						:locale="lang" />
				</li>
			</ol>
		</template>
	</section>
</template>

<script>
import BusyStatus from '../../components/inbox/BusyStatus.vue'
import MessageLanguagePicker from '../../components/inbox/MessageLanguagePicker.vue'
import TranslatedText from '../../components/inbox/TranslatedText.vue'
import { formatDateTime, rowId } from './inbox.js'
import { PAGE_EMITS, PAGE_PROPS } from './pageProps.js'
import { pageLocale, withStrings } from './translate.js'

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
 */
export default {
	name: 'MessagesPage',

	components: { BusyStatus, MessageLanguagePicker, TranslatedText },

	props: PAGE_PROPS,

	emits: PAGE_EMITS,

	data() {
		return {
			threads: null,
			activeId: null,
			messages: null,
			language: '',
			error: '',
		}
	},

	computed: {
		/**
		 * @return {string} `nl` or `en`.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		lang() {
			return pageLocale(this.locale)
		},

		/**
		 * @return {(key: string, vars?: object) => string} The translator.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		tr() {
			return withStrings(this.t, this.lang)
		},
	},

	created() {
		this.load()
	},

	methods: {
		/**
		 * Read the threads and the chosen language, then open the first thread.
		 *
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		async load() {
			const [list, details] = await Promise.all([
				this.api.fetchThreads(),
				this.api.getDetails(),
			])
			this.threads = Array.isArray(list) ? list : []
			this.language = details?.messageLanguage || ''
			if (this.threads.length > 0) {
				await this.choose(rowId(this.threads[0]))
			}
		},

		/**
		 * Open one thread and read its messages.
		 *
		 * @param {string} threadId The thread.
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		async choose(threadId) {
			this.activeId = threadId || null
			if (!threadId) {
				return
			}
			this.messages = null
			this.messages = (await this.api.fetchThreadMessages(threadId)) || []
		},

		/**
		 * Save the picked language, then read the thread again in it.
		 *
		 * @param {string} next The language tag, '' for as written.
		 * @return {Promise<void>}
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		async changeLanguage(next) {
			this.error = ''
			const result = await this.api.setMessageLanguage(next)
			if (!result?.ok) {
				this.error = this.tr('Your language choice could not be saved.')
				return
			}
			this.language = next
			await this.choose(this.activeId)
		},

		/**
		 * @param {object} row A thread or message.
		 * @param {number} [i] Its position.
		 * @return {string|number} Its id.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		idOf(row, i = null) {
			return rowId(row, i)
		},

		/**
		 * @param {object} message A message.
		 * @return {boolean} Whether the reader sent it.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		isOwn(message) {
			return (
				Boolean(this.session?.subjectRef)
				&& message.senderRef === this.session.subjectRef
			)
		},

		/**
		 * @param {string} value An ISO date-time.
		 * @return {string} The value in the page language.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-guardian-must-read-messages-in-their-chosen-language-req-srp-032
		 */
		dateTime(value) {
			return formatDateTime(value, this.lang)
		},
	},
}
</script>

<style scoped>
.pq-messages__threads ul,
.pq-messages__list {
	margin: 0 0 16px;
	padding: 0;
	list-style: none;
}

.pq-messages__threads [aria-current='true'] {
	font-weight: bold;
	text-decoration: underline;
}

.pq-message {
	padding-block: 8px;
	border-block-end: 1px solid var(--utrecht-color-grey-80, currentcolor);
}

.pq-message__header {
	display: flex;
	gap: 8px;
}
</style>
