// src/portal/components/SchemaForm.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// Manifest-driven form (Phase 3). Renders exactly the action's WHITELISTED
// `fields`, shaped by the contribution-manifest-v3 UI-config: `fieldConfigs`
// (label / required / size / placeholder / help) and `optionsProviders` (static
// options, or a subject-scoped `collection` dropdown fetched through the adapter).
//
// SECURITY: the form can only ever submit the action's whitelisted fields — the
// server re-whitelists regardless, and a `collection` dropdown is populated
// through the subject-scoped endpoint, so it can only offer values the subject
// may already read. `fieldConfigs`/`optionsProviders` for a non-whitelisted field
// were already dropped by the server-side normaliser, so they never reach here.
//
// A field declared `type: file` (assignment-portal-file-upload) renders as a
// file picker. It is never part of the create body: the record is created
// first, then each picked file is uploaded into the field and the server
// writes the reference (src/shared/fileFieldSubmit.js).

import React, { useEffect, useState } from 'react'
import { DEFAULT_MAX_SIZE_MB, fileFields, oversizedFiles, submitWithFiles, uploadFiles } from '../../shared/fileFieldSubmit.js'

// Large/full fields render as a textarea; everything else a single-line input
// (unless an optionsProvider makes it a select).
/**
 *
 * @param cfg
 */
function isMultiline(cfg) {
	return cfg && (cfg.size === 'large' || cfg.size === 'full')
}

/**
 * A translator that only interpolates, for a caller that passes none.
 *
 * @param {string} key The English source string.
 * @param {Record<string, string|number>} [vars] Placeholder values.
 * @return {string} The interpolated string.
 */
function untranslated(key, vars) {
	let text = key
	for (const [name, value] of Object.entries(vars || {})) {
		text = text.replace(`{${name}}`, String(value))
	}
	return text
}

/**
 * The picker for one file field, with the chosen names and the size limit.
 *
 * @param {object} props Props.
 * @param {string} props.id The input id the label points at.
 * @param {object} props.cfg The field config (`multiple`, `accept`, `maxSizeMb`, `disabled`).
 * @param {File[]} props.files The files picked so far.
 * @param {(picked: FileList|null) => void} props.onPick Receives the picked FileList.
 * @param {(key: string, vars?: object) => string} props.t The translator.
 * @return {object} The element.
 * @spec openspec/changes/assignment-portal-file-upload/specs/portal-contribution-contract/spec.md#requirement-the-generic-portal-form-must-render-a-file-field-as-a-file-picker
 */
function FileFieldInput({ id, cfg, files, onPick, t }) {
	const accept = (cfg.accept || []).join(',')
	return (
		<>
			<input
				id={id}
				type="file"
				multiple={cfg.multiple === true}
				accept={accept || undefined}
				disabled={cfg.disabled}
				onChange={(e) => onPick(e.target.files)}
			/>
			{files.length > 0 && (
				<small className="portaliq-help">
					{t('Selected: {files}', { files: files.map((f) => f.name).join(', ') })}
				</small>
			)}
			<small className="portaliq-help">
				{t('Up to {size} MB per file', { size: cfg.maxSizeMb || DEFAULT_MAX_SIZE_MB })}
			</small>
		</>
	)
}

/**
 *
 * @param root0
 * @param root0.action
 * @param root0.api
 * @param root0.onSubmitted
 * @param {(key: string, vars?: object) => string} [root0.t] Optional translator; without one the English source strings render.
 */
export default function SchemaForm({ action, api, onSubmitted, t }) {
	const translate = t || untranslated
	const fields = action.fields || []
	const fieldConfigs = action.fieldConfigs || {}
	const optionsProviders = action.optionsProviders || {}
	const fileFieldNames = fileFields(action)

	const [values, setValues] = useState({})
	const [options, setOptions] = useState({})
	const [submitting, setSubmitting] = useState(false)
	const [error, setError] = useState(null)
	const [done, setDone] = useState(null)
	// Picked files per file field, and the files of a saved record that did
	// not attach (so they can be tried again against the same record).
	const [files, setFiles] = useState({})
	const [pending, setPending] = useState(null)
	// Bumped to remount the file inputs, which is the only way to clear them.
	const [fileInputKey, setFileInputKey] = useState(0)

	// Resolve `collection` option providers up front (static ones are inline).
	useEffect(() => {
		let cancelled = false
		for (const field of fields) {
			const p = optionsProviders[field]
			if (p && p.type === 'static') {
				setOptions((o) => ({ ...o, [field]: p.options || [] }))
			} else if (p && p.type === 'collection') {
				api.fetchOptions(p).then((opts) => {
					if (!cancelled) {
						setOptions((o) => ({ ...o, [field]: opts }))
					}
				})
			}
		}
		return () => { cancelled = true }
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [action.id])

	/**
	 *
	 * @param field
	 * @param value
	 */
	function setField(field, value) {
		setValues((v) => ({ ...v, [field]: value }))
	}

	/**
	 * Keep the files picked for one file field.
	 *
	 * @param {string} field The file field.
	 * @param {FileList|null} picked The picked files.
	 */
	function setFieldFiles(field, picked) {
		setFiles((f) => ({ ...f, [field]: Array.from(picked || []) }))
	}

	/**
	 * Report files that did not attach, or clear the report when all did.
	 *
	 * @param {string} id The saved record's id.
	 * @param {Array<{field: string, file: File}>} failed The files that did not attach.
	 */
	function reportFailed(id, failed) {
		if (failed.length === 0) {
			setPending(null)
			return
		}
		setPending({ id, failed })
		setError(translate('Saved, but these files were not attached: {files}', { files: failed.map((f) => f.file.name).join(', ') }))
	}

	/**
	 * Try the files that did not attach again, against the same record.
	 */
	async function retryFailed() {
		if (!pending) {
			return
		}
		const byField = {}
		for (const { field, file } of pending.failed) {
			byField[field] = [...(byField[field] || []), file]
		}
		setError(null)
		setSubmitting(true)
		const { failed } = await uploadFiles(api, action, pending.id, byField)
		setSubmitting(false)
		reportFailed(pending.id, failed)
		if (failed.length === 0) {
			setDone(translate('All files are attached.'))
		}
	}

	/**
	 *
	 * @param e
	 */
	async function submit(e) {
		e.preventDefault()
		setError(null)
		setDone(null)
		// Read the LIVE field values from the form element at submit time rather
		// than the React `values` state: a controlled input's onChange state
		// update can still be in flight on the first submit (it commits a render
		// behind), which would make a just-filled required field read as empty.
		// The DOM is the source of truth here; `values` is only the fallback.
		const formEl = e.currentTarget
		const submitValues = {}
		for (const field of fields) {
			if (fileFieldNames.includes(field)) {
				continue
			}
			const el = formEl.querySelector(`#f-${action.id}-${field}`)
			submitValues[field] = (el ? el.value : values[field]) ?? ''
		}
		// Client-side required check (the server is the authority regardless).
		for (const field of fields) {
			if (fileFieldNames.includes(field)) {
				if (fieldConfigs[field]?.required && (files[field] || []).length === 0) {
					setError(translate('Please choose a file for {field}.', { field: fieldConfigs[field]?.label || field }))
					return
				}
				continue
			}
			if (fieldConfigs[field]?.required && !submitValues[field]) {
				setError(`${fieldConfigs[field]?.label || field} is verplicht.`)
				return
			}
		}
		// Refuse an oversized file before the record is saved; the server
		// checks the same limit again.
		const tooLarge = oversizedFiles(action, files)
		if (tooLarge.length > 0) {
			setError(translate('These files are too large: {files}', { files: tooLarge.join(', ') }))
			return
		}
		setSubmitting(true)
		const result = await submitWithFiles(api, action, submitValues, files)
		setSubmitting(false)
		if (!result.ok) {
			setError('Opslaan is niet gelukt.')
			return
		}
		setValues({})
		setFiles({})
		setFileInputKey((k) => k + 1)
		reportFailed(result.id, result.failed)
		if (result.failed.length === 0) {
			setDone(action.successMessage || 'Opgeslagen.')
		}
		if (onSubmitted) {
			onSubmitted(result.object, action)
		}
	}

	return (
		<form className="portaliq-form" onSubmit={submit}>
			{fields.map((field) => {
				const cfg = fieldConfigs[field] || {}
				const label = cfg.label || field
				const opts = options[field]
				return (
					<div key={field} className={`portaliq-field portaliq-field-${cfg.size || 'medium'}`}>
						<label htmlFor={`f-${action.id}-${field}`}>
							{label}{cfg.required ? ' *' : ''}
						</label>
						{fileFieldNames.includes(field)
							? (
								<FileFieldInput
									key={`${field}-${fileInputKey}`}
									id={`f-${action.id}-${field}`}
									cfg={cfg}
									files={files[field] || []}
									onPick={(picked) => setFieldFiles(field, picked)}
									t={translate}
								/>
							)
							: opts
							? (
								<select
									id={`f-${action.id}-${field}`}
									value={values[field] || ''}
									disabled={cfg.disabled}
									onChange={(e) => setField(field, e.target.value)}
								>
									<option value="">—</option>
									{opts.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
								</select>
							)
							: isMultiline(cfg)
								? (
									<textarea
										id={`f-${action.id}-${field}`}
										value={values[field] || ''}
										placeholder={cfg.placeholder || ''}
										disabled={cfg.disabled}
										onChange={(e) => setField(field, e.target.value)}
									/>
								)
								: (
									<input
										id={`f-${action.id}-${field}`}
										type="text"
										value={values[field] || ''}
										placeholder={cfg.placeholder || ''}
										disabled={cfg.disabled}
										onChange={(e) => setField(field, e.target.value)}
									/>
								)}
						{cfg.help && <small className="portaliq-help">{cfg.help}</small>}
					</div>
				)
			})}
			<div className="portaliq-form-actions">
				<button type="submit" disabled={submitting}>
					{submitting ? '…' : (action.submitLabel || action.label || 'Opslaan')}
				</button>
			</div>
			{error && <p className="portaliq-error" role="alert">{error}</p>}
			{pending && (
				<button type="button" disabled={submitting} onClick={retryFailed}>
					{translate('Try these files again')}
				</button>
			)}
			{done && <p className="portaliq-success">{done}</p>}
		</form>
	)
}

// src/site/components/c/SchemaForm.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<template>
	<form
		class="pq-schema-form"
		:aria-label="action.label || action.id"
		data-testid="schema-form"
		novalidate
		@submit.prevent="submit">
		<p
			v-if="error !== ''"
			class="utrecht-paragraph pq-schema-form__error"
			role="alert"
			data-testid="schema-form-error">
			{{ error }}
		</p>

		<SchemaField
			v-for="field in fields"
			:id="inputId(field)"
			:key="field"
			v-model="values[field]"
			:field="field"
			:label="labelOf(field)"
			:config="configOf(field)"
			:input="inputOf(field)"
			:options="options[field] || []"
			:files="files[field] || []"
			:fileKey="fileKey"
			:error="errors[field] || ''"
			:t="t"
			@pick="(picked) => pick(field, picked)" />

		<div class="pq-schema-form__buttons">
			<button
				type="submit"
				class="utrecht-button utrecht-button--primary-action"
				:disabled="submitting"
				data-testid="schema-form-submit">
				{{ submitting ? translate('Please wait…') : submitLabel }}
			</button>
			<button
				v-if="pending !== null"
				type="button"
				class="utrecht-button utrecht-button--secondary-action"
				:disabled="submitting"
				data-testid="schema-form-retry"
				@click="retryFailed">
				{{ translate('Try these files again') }}
			</button>
		</div>

		<p
			class="utrecht-paragraph pq-schema-form__done"
			role="status"
			data-testid="schema-form-done">
			{{ done }}
		</p>
	</form>
</template>

<script>
import SchemaField from './SchemaField.vue'
import {
	oversizedFiles,
	submitWithFiles,
	uploadFiles,
} from '../../../shared/fileFieldSubmit.js'
import {
	collectionProviders,
	fieldConfig,
	fieldErrors,
	fieldInput,
	fieldLabel,
	formBody,
	formFields,
	staticOptions,
	translatorOr,
} from './forms.js'

/**
 * A manifest-driven form (the Vue port of SchemaForm.jsx, which also replaces
 * ActionFieldsForm.jsx). It renders exactly the action's whitelisted `fields`,
 * shaped by `fieldConfigs` and `optionsProviders`: a static list, or a
 * collection fetched through the subject-scoped api, so a dropdown only offers
 * what the resident may already read. A file field is never in the create
 * body: the record is created first, then each file is uploaded into it.
 *
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-schema-form-must-render-only-whitelisted-fields-req-srp-022
 */
export default {
	name: 'SchemaForm',

	components: { SchemaField },

	props: {
		/** The normalised manifest action (`create` or `update`). */
		action: { type: Object, required: true },
		/** The portal api: `createObject`, `uploadFieldFile`, `fetchOptions`. */
		api: { type: Object, required: true },
		/** The translator `t(key, vars)`. */
		t: { type: Function, default: null },
	},

	emits: ['submitted'],

	data() {
		return {
			values: this.emptyValues(),
			options: staticOptions(this.action),
			files: {},
			fileKey: 0,
			errors: {},
			error: '',
			done: '',
			submitting: false,
			pending: null,
		}
	},

	computed: {
		translate() {
			return translatorOr(this.t)
		},

		fields() {
			return formFields(this.action)
		},

		submitLabel() {
			return (
				this.action.submitLabel
				|| this.action.label
				|| this.translate('Save')
			)
		},
	},

	watch: {
		'action.id': function () {
			this.values = this.emptyValues()
			this.options = staticOptions(this.action)
			this.loadOptions()
		},
	},

	mounted() {
		this.loadOptions()
	},

	methods: {
		/**
		 * One empty string per whitelisted field.
		 *
		 * @return {Record<string, string>} The values.
		 */
		emptyValues() {
			const values = {}
			for (const field of formFields(this.action)) {
				values[field] = ''
			}
			return values
		},

		/**
		 * Fetch every `collection` provider's options.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-schema-form-must-render-only-whitelisted-fields-req-srp-022
		 */
		async loadOptions() {
			const actionId = this.action.id
			await Promise.all(
				collectionProviders(this.action).map(async ([field, provider]) => {
					const fetched = await this.api.fetchOptions(provider)
					if (this.action.id === actionId) {
						this.options = {
							...this.options,
							[field]: Array.isArray(fetched) ? fetched : [],
						}
					}
				}),
			)
		},

		inputId(field) {
			return `f-${this.action.id}-${field}`
		},

		labelOf(field) {
			return fieldLabel(this.action, field)
		},

		configOf(field) {
			return fieldConfig(this.action, field)
		},

		inputOf(field) {
			return fieldInput(this.action, field, this.options[field])
		},

		/**
		 * Keep the files picked for one file field.
		 *
		 * @param {string} field The file field.
		 * @param {FileList|null} picked The picked files.
		 */
		pick(field, picked) {
			this.files = { ...this.files, [field]: Array.from(picked || []) }
		},

		/**
		 * Move focus to the first field with an error.
		 */
		focusFirstError() {
			const first = this.fields.find((field) => this.errors[field])
			const element =
				first && typeof document !== 'undefined'
					? document.getElementById(this.inputId(first))
					: null
			if (element) {
				element.focus()
			}
		},

		/**
		 * Report files that did not attach, or clear the report.
		 *
		 * @param {string} id The saved record's id.
		 * @param {Array<{field: string, file: File}>} failed The files that did not attach.
		 */
		reportFailed(id, failed) {
			if (failed.length === 0) {
				this.pending = null
				return
			}
			this.pending = { id, failed }
			this.error = this.translate(
				'Saved, but these files were not attached: {files}',
				{ files: failed.map((f) => f.file.name).join(', ') },
			)
		},

		/**
		 * Try the files that did not attach again, against the same record.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-file-field-must-upload-after-the-record-exists-req-srp-023
		 */
		async retryFailed() {
			if (this.pending === null) {
				return
			}
			const byField = {}
			for (const { field, file } of this.pending.failed) {
				byField[field] = [...(byField[field] || []), file]
			}
			this.error = ''
			this.submitting = true
			const { failed } = await uploadFiles(
				this.api,
				this.action,
				this.pending.id,
				byField,
			)
			this.submitting = false
			this.reportFailed(this.pending.id, failed)
			if (failed.length === 0) {
				this.done = this.translate('All files are attached.')
			}
		},

		/**
		 * Check, create the record, then upload its files.
		 *
		 * @return {Promise<void>}
		 *
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-file-field-must-upload-after-the-record-exists-req-srp-023
		 */
		async submit() {
			this.error = ''
			this.done = ''
			this.errors = fieldErrors(this.action, this.values, this.files, this.t)
			if (Object.keys(this.errors).length > 0) {
				this.error = this.translate(
					'Not everything is filled in yet. Check the fields below.',
				)
				this.$nextTick(() => this.focusFirstError())
				return
			}
			const tooLarge = oversizedFiles(this.action, this.files)
			if (tooLarge.length > 0) {
				this.error = this.translate('These files are too large: {files}', {
					files: tooLarge.join(', '),
				})
				return
			}

			this.submitting = true
			const result = await submitWithFiles(
				this.api,
				this.action,
				formBody(this.action, this.values, this.options),
				this.files,
			)
			this.submitting = false
			if (!result.ok) {
				this.error = this.translate('Saving did not work.')
				return
			}

			this.values = this.emptyValues()
			this.files = {}
			this.fileKey++
			this.reportFailed(result.id, result.failed)
			if (result.failed.length === 0) {
				this.done = this.action.successMessage || this.translate('Saved.')
			}
			this.$emit('submitted', result.object, this.action)
		},
	},
}
</script>

<style scoped>
.pq-schema-form {
	display: block;
	margin-block: var(--utrecht-space-block-md, 1rem);
}

.pq-schema-form__buttons {
	display: flex;
	flex-wrap: wrap;
	gap: var(--utrecht-space-inline-sm, 0.5rem);
	margin-block-start: var(--utrecht-space-block-md, 1rem);
}

.pq-schema-form__error {
	color: var(--utrecht-form-field-error-message-color, inherit);
	font-weight: var(--utrecht-typography-weight-scale-bold, bold);
}

.pq-schema-form__done:empty {
	display: none;
}
</style>
