// src/portal/components/TranslatedText.jsx
// SPDX-License-Identifier: EUPL-1.2
// Copyright (C) 2026 Conduction B.V.
//
// A message text that may have been translated by AI (translated-message-notice,
// decision D24). With a labelled `translation` the reader sees the translation,
// then a notice "Translated by AI from Dutch" in an `aside` landmark with a mark
// and text (never colour alone), and a button that shows the original in place.
// Without one, the text renders as written and no notice appears.

import { useState } from 'react'

/**
 * The name of a language, written in the portal's language. Falls back to
 * the upper-cased tag where the browser cannot name it.
 *
 * @param {string} tag A BCP-47 tag such as `nl` or `pt-BR`.
 * @param {string} locale The portal's locale, such as `en` or `nl`.
 * @return {string} The language's name.
 */
export function languageLabel(tag, locale) {
	if (!tag) {
		return ''
	}
	try {
		const names = new Intl.DisplayNames([locale || 'en'], { type: 'language' })
		const name = names.of(tag)
		if (name && name.toLowerCase() !== tag.toLowerCase()) {
			return name
		}
	} catch {
		// No Intl.DisplayNames, or a tag it refuses: fall through to the tag.
	}
	return String(tag).toUpperCase()
}

/**
 * The notice sentence for a translation.
 *
 * @param {object} translation The `translation` entry.
 * @param {(key: string, vars?: object) => string} t The portal translator.
 * @param {string} locale The portal's locale.
 * @return {string} "Translated by AI from <language>", or "Translated by AI" for `und`.
 */
export function noticeText(translation, t, locale) {
	const source = translation.sourceLanguage || 'und'
	if (source === 'und') {
		return t('Translated by AI')
	}
	return t('Translated by AI from {language}', { language: languageLabel(source, locale) })
}

/**
 * Whether a `translation` entry is a labelled AI translation worth showing.
 *
 * @param {object|undefined} translation The entry.
 * @return {boolean}
 */
export function isLabelledTranslation(translation) {
	return Boolean(translation && translation.translatedByAi === true && typeof translation.text === 'string' && translation.text !== '')
}

/**
 * @param {object} props The props.
 * @param {string} props.text The text as written.
 * @param {object} [props.translation] The reader's translation entry, if any.
 * @param {(key: string, vars?: object) => string} props.t The portal translator.
 * @param {string} props.locale The portal's locale.
 * @param {string} props.id A stable id for this message, used to wire the button to the original.
 * @param {string} [props.bodyClassName] Class for the shown text.
 * @param {boolean} [props.defaultOpen] Start with the original shown.
 * @param {string} [props.originalTitle] A title translated with the text (a news
 *     item's): the original then shows it above the text, under the same notice.
 * @param {string} [props.as] The element the shown text renders in, `p` by
 *     default; a heading (a newsletter's title) keeps its level this way.
 */
export default function TranslatedText({ text, translation, t, locale, id, bodyClassName = 'portaliq-message__body', defaultOpen = false, originalTitle, as: Shown = 'p' }) {
	const [open, setOpen] = useState(defaultOpen)

	if (!isLabelledTranslation(translation)) {
		return <Shown className={bodyClassName}>{text}</Shown>
	}

	const originalId = `portaliq-original-${String(id).replace(/[^A-Za-z0-9_-]/g, '-')}`
	const source = translation.sourceLanguage && translation.sourceLanguage !== 'und' ? translation.sourceLanguage : undefined

	return (
		<div className="portaliq-translated">
			<Shown className={bodyClassName} lang={translation.targetLanguage}>{translation.text}</Shown>
			<aside className="portaliq-ai-notice" aria-label={t('AI translation')}>
				<span className="portaliq-ai-notice__mark" aria-hidden="true">AI</span>
				<span className="portaliq-ai-notice__text">{noticeText(translation, t, locale)}</span>
				{translation.disclosure && (
					<span className="portaliq-ai-notice__disclosure" lang={translation.disclosureLanguage || undefined}>
						{translation.disclosure}
					</span>
				)}
				<button
					type="button"
					className="portaliq-ai-notice__toggle"
					aria-expanded={open ? 'true' : 'false'}
					aria-controls={originalId}
					onClick={() => setOpen(!open)}
				>
					{open ? t('Hide the original text') : t('Show the original text')}
				</button>
			</aside>
			<blockquote id={originalId} className="portaliq-translated__original" lang={source} hidden={!open}>
				{originalTitle
					? (
						<>
							<p className="portaliq-translated__original-title">{originalTitle}</p>
							<p>{text}</p>
						</>
					)
					: text}
			</blockquote>
		</div>
	)
}

// src/site/components/inbox/TranslatedText.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	A text AI may have translated (translated-message-notice, decision D24).
	With a labelled translation the reader sees the translation, then a notice
	"Translated by AI from Dutch" in an aside landmark, with a mark and text
	(never colour alone), and a button that shows the original in place.
	Without one, the text shows as written and no notice appears.
-->
<template>
	<component :is="as" v-if="!labelled" :class="bodyClass">
		{{ text }}
	</component>
	<div v-else class="pq-translated">
		<component :is="as" :class="bodyClass" :lang="translation.targetLanguage">
			{{ translation.text }}
		</component>
		<aside class="pq-ai-notice" :aria-label="t('AI translation')">
			<span class="pq-ai-notice__mark" aria-hidden="true">AI</span>
			<span class="pq-ai-notice__text">{{ notice }}</span>
			<span
				v-if="translation.disclosure"
				class="pq-ai-notice__disclosure"
				:lang="translation.disclosureLanguage || undefined">
				{{ translation.disclosure }}
			</span>
			<button
				type="button"
				class="utrecht-button utrecht-button--subtle pq-ai-notice__toggle"
				:aria-expanded="open ? 'true' : 'false'"
				:aria-controls="originalElementId"
				@click="open = !open">
				{{
					open ? t('Hide the original text') : t('Show the original text')
				}}
			</button>
		</aside>
		<blockquote
			:id="originalElementId"
			class="pq-translated__original"
			:lang="sourceLanguage"
			:hidden="!open">
			<template v-if="originalTitle">
				<p class="utrecht-paragraph pq-translated__original-title">
					{{ originalTitle }}
				</p>
				<p class="utrecht-paragraph">{{ text }}</p>
			</template>
			<template v-else>{{ text }}</template>
		</blockquote>
	</div>
</template>

<script>
import {
	isLabelledTranslation,
	noticeText,
	originalId,
} from '../../pages/inbox/translation.js'

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-machine-translation-must-say-so-req-srp-034
 */
export default {
	name: 'TranslatedText',

	props: {
		/** The text as written. */
		text: { type: String, default: '' },
		/** The reader's translation entry, if any. */
		translation: { type: Object, default: null },
		/** The translator. */
		t: { type: Function, required: true },
		/** The page language. */
		locale: { type: String, default: 'nl' },
		/** A stable id, used to wire the button to the original. */
		id: { type: [String, Number], required: true },
		/** Class of the shown text. */
		bodyClass: { type: String, default: 'utrecht-paragraph pq-message__body' },
		/** Start with the original shown. */
		defaultOpen: { type: Boolean, default: false },
		/** A title translated with the text: the original shows it above the text. */
		originalTitle: { type: String, default: '' },
		/** The element the shown text renders in; a heading keeps its level. */
		as: { type: String, default: 'p' },
	},

	data() {
		return { open: this.defaultOpen }
	},

	computed: {
		/**
		 * @return {boolean} Whether a labelled translation is there.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-machine-translation-must-say-so-req-srp-034
		 */
		labelled() {
			return isLabelledTranslation(this.translation)
		},

		/**
		 * @return {string} The notice sentence.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-machine-translation-must-say-so-req-srp-034
		 */
		notice() {
			return noticeText(this.translation, this.t, this.locale)
		},

		/**
		 * @return {string} The id of the original's element.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-machine-translation-must-say-so-req-srp-034
		 */
		originalElementId() {
			return originalId(this.id)
		},

		/**
		 * @return {string|undefined} The original's language, never an invented one.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-machine-translation-must-say-so-req-srp-034
		 */
		sourceLanguage() {
			const source = this.translation?.sourceLanguage
			return source && source !== 'und' ? source : undefined
		},
	},
}
</script>

<style scoped>
.pq-ai-notice {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	gap: 8px;
	margin-block: 4px 8px;
	font-size: 0.9em;
	color: var(--utrecht-paragraph-color, inherit);
}

.pq-ai-notice__mark {
	padding: 0 6px;
	border: 1px solid currentcolor;
	border-radius: 4px;
	font-weight: bold;
}

.pq-translated__original {
	margin: 0 0 8px;
	padding-inline-start: 12px;
	border-inline-start: 3px solid var(--utrecht-color-grey-60, currentcolor);
}
</style>
