// src/portal/components/TimedTaskItem.jsx
// SPDX-License-Identifier: EUPL-1.2
//
// One question of a timed task (portal-take-assessment), rendered by type:
// radio buttons for a choice, a select for an inline choice, an input for a
// text entry, a textarea for extended text, a list with move buttons for an
// order, a select per source for a match, and a text answer for any other
// type. The leaf app sent the prompt as plain text and the options in
// presentation order; nothing here can reveal an answer.

import { move, renderAs } from '../../shared/timedTask.js'

/**
 * @param {object} props Props.
 * @param {object} props.item The normalised item.
 * @param {string|Array<string>|Object<string, string>} props.value The current answer.
 * @param {(value: string|Array<string>|Object<string, string>) => void} props.onChange Receives the new answer.
 * @param {(key: string, vars?: object) => string} props.t The translator.
 * @param {boolean} [props.disabled] Whether answering is closed.
 * @return {object} The element.
 * @spec openspec/changes/portal-take-assessment/specs/portal-contribution-contract/spec.md#requirement-the-portal-must-let-a-subject-take-a-timed-task
 */
export default function TimedTaskItem({ item, value, onChange, t, disabled = false }) {
	const id = `tt-${item.itemId}`
	const as = renderAs(item)

	if (as === 'choice') {
		return (
			<fieldset className="portaliq-field portaliq-timedtask-item" disabled={disabled}>
				<legend>{item.prompt}</legend>
				{item.choices.map((choice) => (
					<label key={choice.id} className="portaliq-timedtask-choice">
						<input
							type="radio"
							name={id}
							value={choice.id}
							checked={value === choice.id}
							onChange={() => onChange(choice.id)}
						/>
						{choice.label}
					</label>
				))}
			</fieldset>
		)
	}

	if (as === 'inlineChoice') {
		return (
			<div className="portaliq-field portaliq-timedtask-item">
				<label htmlFor={id}>{item.prompt}</label>
				<select id={id} value={value || ''} disabled={disabled} onChange={(e) => onChange(e.target.value)}>
					<option value="">{t('Choose')}</option>
					{item.choices.map((choice) => <option key={choice.id} value={choice.id}>{choice.label}</option>)}
				</select>
			</div>
		)
	}

	if (as === 'textEntry') {
		return (
			<div className="portaliq-field portaliq-timedtask-item">
				<label htmlFor={id}>{item.prompt}</label>
				<input id={id} type="text" value={value || ''} disabled={disabled} onChange={(e) => onChange(e.target.value)} />
			</div>
		)
	}

	if (as === 'order') {
		const order = Array.isArray(value) ? value : []
		const labels = new Map(item.choices.map((c) => [c.id, c.label]))
		return (
			<div className="portaliq-field portaliq-timedtask-item">
				<p id={`${id}-prompt`}>{item.prompt}</p>
				<ol aria-labelledby={`${id}-prompt`} className="portaliq-timedtask-order">
					{order.map((optionId, index) => (
						<li key={optionId}>
							<span>{labels.get(optionId) || optionId}</span>
							<button type="button" disabled={disabled || index === 0} onClick={() => onChange(move(order, index, -1))}>
								{t('Move up')}
							</button>
							<button type="button" disabled={disabled || index === order.length - 1} onClick={() => onChange(move(order, index, 1))}>
								{t('Move down')}
							</button>
						</li>
					))}
				</ol>
			</div>
		)
	}

	if (as === 'match') {
		const pairs = value && typeof value === 'object' ? value : {}
		return (
			<fieldset className="portaliq-field portaliq-timedtask-item" disabled={disabled}>
				<legend>{item.prompt}</legend>
				{item.sources.map((source) => (
					<div key={source.id} className="portaliq-timedtask-match">
						<label htmlFor={`${id}-${source.id}`}>{source.label}</label>
						<select
							id={`${id}-${source.id}`}
							value={pairs[source.id] || ''}
							onChange={(e) => onChange({ ...pairs, [source.id]: e.target.value })}
						>
							<option value="">{t('Choose')}</option>
							{item.targets.map((target) => <option key={target.id} value={target.id}>{target.label}</option>)}
						</select>
					</div>
				))}
			</fieldset>
		)
	}

	// extendedText, and the text answer for every other type.
	return (
		<div className="portaliq-field portaliq-timedtask-item">
			<label htmlFor={id}>{item.prompt}</label>
			<textarea
				id={id}
				rows={as === 'extendedText' ? 10 : 4}
				value={typeof value === 'string' ? value : ''}
				placeholder={t('Type your answer')}
				disabled={disabled}
				onChange={(e) => onChange(e.target.value)}
			/>
			{as === 'extendedText' && <small className="portaliq-help">{t('Your teacher marks this question.')}</small>}
		</div>
	)
}

// src/site/components/timed-task/TimedTaskItem.vue
<!--
  - SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
  - SPDX-License-Identifier: EUPL-1.2
  -->

<!--
	One question of a timed task (portal-take-assessment), by type: radio
	buttons for a choice, a select for an inline choice, an input for a text
	entry, a textarea for extended text, a list with move buttons for an order,
	a select per source for a match, and a text answer for any other type. The
	leaf app sends the prompt as plain text and the options in presentation
	order; nothing here can reveal an answer.
-->
<template>
	<fieldset
		v-if="as === 'choice'"
		class="utrecht-form-fieldset pq-timedtask-item"
		:disabled="disabled">
		<legend class="utrecht-form-fieldset__legend">{{ item.prompt }}</legend>
		<label
			v-for="choice in item.choices"
			:key="choice.id"
			class="utrecht-form-label utrecht-form-label--radio pq-timedtask-choice">
			<input
				type="radio"
				class="utrecht-radio-button"
				:name="id"
				:value="choice.id"
				:checked="value === choice.id"
				@change="$emit('change', choice.id)" />
			{{ choice.label }}
		</label>
	</fieldset>

	<div
		v-else-if="as === 'inlineChoice'"
		class="utrecht-form-field pq-timedtask-item">
		<label class="utrecht-form-label" :for="id">{{ item.prompt }}</label>
		<select
			:id="id"
			class="utrecht-select"
			:value="value || ''"
			:disabled="disabled"
			@change="$emit('change', $event.target.value)">
			<option value="">{{ t('Choose') }}</option>
			<option
				v-for="choice in item.choices"
				:key="choice.id"
				:value="choice.id">
				{{ choice.label }}
			</option>
		</select>
	</div>

	<div v-else-if="as === 'textEntry'" class="utrecht-form-field pq-timedtask-item">
		<label class="utrecht-form-label" :for="id">{{ item.prompt }}</label>
		<input
			:id="id"
			type="text"
			class="utrecht-textbox"
			:value="value || ''"
			:disabled="disabled"
			@input="$emit('change', $event.target.value)" />
	</div>

	<div v-else-if="as === 'order'" class="utrecht-form-field pq-timedtask-item">
		<p :id="`${id}-prompt`" class="utrecht-paragraph">{{ item.prompt }}</p>
		<ol :aria-labelledby="`${id}-prompt`" class="pq-timedtask-order">
			<li v-for="(optionId, index) in order" :key="optionId">
				<span>{{ labelOf(optionId) }}</span>
				<button
					type="button"
					class="utrecht-button utrecht-button--subtle"
					:disabled="disabled || index === 0"
					@click="$emit('change', moved(index, -1))">
					{{ t('Move up') }}
				</button>
				<button
					type="button"
					class="utrecht-button utrecht-button--subtle"
					:disabled="disabled || index === order.length - 1"
					@click="$emit('change', moved(index, 1))">
					{{ t('Move down') }}
				</button>
			</li>
		</ol>
	</div>

	<fieldset
		v-else-if="as === 'match'"
		class="utrecht-form-fieldset pq-timedtask-item"
		:disabled="disabled">
		<legend class="utrecht-form-fieldset__legend">{{ item.prompt }}</legend>
		<div
			v-for="source in item.sources"
			:key="source.id"
			class="utrecht-form-field pq-timedtask-match">
			<label class="utrecht-form-label" :for="`${id}-${source.id}`">{{
				source.label
			}}</label>
			<select
				:id="`${id}-${source.id}`"
				class="utrecht-select"
				:value="pairs[source.id] || ''"
				@change="
					$emit('change', { ...pairs, [source.id]: $event.target.value })
				">
				<option value="">{{ t('Choose') }}</option>
				<option
					v-for="target in item.targets"
					:key="target.id"
					:value="target.id">
					{{ target.label }}
				</option>
			</select>
		</div>
	</fieldset>

	<div v-else class="utrecht-form-field pq-timedtask-item">
		<label class="utrecht-form-label" :for="id">{{ item.prompt }}</label>
		<textarea
			:id="id"
			class="utrecht-textarea"
			:rows="as === 'extendedText' ? 10 : 4"
			:value="typeof value === 'string' ? value : ''"
			:placeholder="t('Type your answer')"
			:disabled="disabled"
			:aria-describedby="as === 'extendedText' ? `${id}-help` : undefined"
			@input="$emit('change', $event.target.value)" />
		<p
			v-if="as === 'extendedText'"
			:id="`${id}-help`"
			class="utrecht-paragraph pq-help">
			{{ t('Your teacher marks this question.') }}
		</p>
	</div>
</template>

<script>
import { move, renderAs } from '../../../shared/timedTask.js'

/**
 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
 */
export default {
	name: 'TimedTaskItem',

	props: {
		/** The normalised item. */
		item: { type: Object, required: true },
		/** The current answer. */
		value: { type: [String, Array, Object], default: '' },
		/** The translator. */
		t: { type: Function, required: true },
		/** Whether answering is closed. */
		disabled: { type: Boolean, default: false },
	},

	emits: ['change'],

	computed: {
		/**
		 * @return {string} The element ids' stem.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		id() {
			return `tt-${this.item.itemId}`
		},

		/**
		 * @return {string} How the item renders.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		as() {
			return renderAs(this.item)
		},

		/**
		 * @return {Array<string>} The current order.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		order() {
			return Array.isArray(this.value) ? this.value : []
		},

		/**
		 * @return {Record<string, string>} The current pairs.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		pairs() {
			return this.value
				&& typeof this.value === 'object'
				&& !Array.isArray(this.value)
				? this.value
				: {}
		},
	},

	methods: {
		/**
		 * @param {string} optionId An option.
		 * @return {string} Its label.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		labelOf(optionId) {
			return (
				(this.item.choices || []).find((c) => c.id === optionId)?.label
				|| optionId
			)
		},

		/**
		 * @param {number} index The option's place.
		 * @param {number} step -1 up, 1 down.
		 * @return {Array<string>} The new order.
		 * @spec openspec/changes/site-reaches-portal-parity/specs/site-portal-parity/spec.md#requirement-a-pupil-must-be-able-to-take-a-timed-task-req-srp-036
		 */
		moved(index, step) {
			return move(this.order, index, step)
		},
	},
}
</script>
